#!/bin/bash

if [[ "$1" != https://github.com/* ]]; then
	echo "$1 does not look like a pull request URL"
	exit 1
fi

endpoint=$(echo $1 | cut -d'/' -f 4,5)
pull_id=$(echo $1 | cut -d'/' -f 7)
target_branch=$2

# Get the data on the original pull request

repo_url=git@github.com:${endpoint}.git

if [ "" == "$target_branch" ]; then
	target_branch=$(curl -H "Authorization: token $(git config github.oauth-token)" -s https://api.github.com/repos/$endpoint/pulls/$pull_id | jq '.head.ref' | tr -d '"')
fi

if [ "" != "$(git for-each-ref --format='%(refname)' refs/heads/ | cut -d'/' -f 3 | grep "^${target_branch}$")" ]; then
	echo "Already have a branch named $target_branch"
	return 1
fi

git fetch --no-tags ${repo_url} pull/${pull_id}/head:${target_branch}
git checkout $target_branch