#!/bin/bash

copy_driver() {
	if [ "" == "${CATALINA_HOME}" ]; then
		mkdir -p ${LIFERAY_HOME}/tomcat/lib/ext
		CATALINA_HOME=${LIFERAY_HOME}/tomcat
	fi

	local DRIVER_CLASS_NAME="$(grep -F jdbc.default.driverClassName ${LIFERAY_HOME}/portal-ext.properties | grep -vF '#' | cut -d'=' -f 2)"

	if [ "org.mariadb.jdbc.Driver" == "${DRIVER_CLASS_NAME}" ]; then
		DRIVER='mariadb.jar'
	elif [ "com.mysql.jdbc.Driver" == "${DRIVER_CLASS_NAME}" ]; then
		DRIVER='mysql.jar'
	elif [ "oracle.jdbc.OracleDriver" == "${DRIVER_CLASS_NAME}" ]; then
		DRIVER='ojdbc7_g.jar'
	elif [ "org.postgresql.Driver" == "${DRIVER_CLASS_NAME}" ]; then
		DRIVER='postgresql.jar'
	elif [ "com.microsoft.sqlserver.jdbc.SQLServerDriver" == "${DRIVER_CLASS_NAME}" ]; then
		if [[ ${HOTFIX_LEVEL} == 6.1.* ]] || [[ ${HOTFIX_LEVEL} == *-6130 ]] || [[ ${HOTFIX_LEVEL} == *-6130.zip ]]; then
			DRIVER='mssql-jdbc-6.2.2.jre7.jar'
		elif [[ ${HOTFIX_LEVEL} == portal-* ]] || [[ ${HOTFIX_LEVEL} == 6.2.* ]] || [[ ${HOTFIX_LEVEL} == *-6210 ]] || [[ ${HOTFIX_LEVEL} == *-6210.zip ]]; then
			DRIVER='mssql-jdbc-6.2.2.jre7.jar'
		else
			DRIVER='mssql-jdbc-6.2.2.jre8.jar'
		fi
	elif [ "com.sybase.jdbc4.jdbc.SybDriver" == "${DRIVER_CLASS_NAME}" ]; then
		DRIVER='jconn4.jar'
	else
		echo "Unable to guess .jar name for ${DRIVER_CLASS_NAME}"
		echo "Hopefully driver is already in ${CATALINA_HOME}/lib/ext"
		return 0
	fi

	if [ -f ${CATALINA_HOME}/lib/ext/${DRIVER} ]; then
		echo "Using existing ${DRIVER} in ${CATALINA_HOME}/lib/ext"
	elif [ "" == "${DRIVERS_FOLDER}" ]; then
		echo "DRIVERS_FOLDER environment variable not set"
		echo "Hopefully driver is already in ${CATALINA_HOME}/lib/ext"
	elif [ ! -f ${DRIVERS_FOLDER}/${DRIVER} ]; then
		echo "${DRIVER} not found. Please download it and copy it to ${DRIVERS_FOLDER}"
	else
		echo "Copying ${DRIVER} from ${DRIVERS_FOLDER} to ${CATALINA_HOME}/lib/ext"
		cp ${DRIVERS_FOLDER}/${DRIVER} ${CATALINA_HOME}/lib/ext
	fi
}

create_network() {
	NETWORK_METADATA=

	if [ "" == "${NETWORK_NAME}" ]; then
		return 0
	fi

	if [ -d ${LIFERAY_HOME}/osgi/portal ] && [ ! -f ${LIFERAY_HOME}/osgi/portal/com.liferay.portal.cluster.multiple.jar ]; then
		echo "Unable to find clustering module in ${LIFERAY_HOME}."
		echo "Are you sure built a private branch?"
		return 1
	fi

	if [ ! -f ${LIFERAY_HOME}/portal-ext.properties ] || [ "" == "$(grep -F jdbc.default ${LIFERAY_HOME}/portal-ext.properties | grep -vF '#')" ]; then
		echo "You need to have a portal-ext.properties with a database connection to cluster."
		return 1
	fi

	if docker network inspect ${NETWORK_NAME} 1> /dev/null 2> /dev/null; then
		echo ${CONTAINER_NAME} will join the existing ${NETWORK_NAME} network
	else
		echo ${CONTAINER_NAME} will join the newly-created ${NETWORK_NAME} network
		docker network create ${NETWORK_NAME}
	fi

	NETWORK_METADATA="--network ${NETWORK_NAME} --network-alias ${CONTAINER_NAME} -e IS_CLUSTER=true"
}

remove_container() {
	docker stop ${CONTAINER_NAME} 1> /dev/null 2> /dev/null
	docker rm -v ${CONTAINER_NAME} 1> /dev/null 2> /dev/null
}

set_container_mounts() {
	mkdir -p ${HOME}/.liferay/builds

	LIFERAY_RDBUILD_MOUNT="-v ${HOME}/.liferay/builds:/rdbuild"

	mkdir -p ${HOME}/.liferay/release

	LIFERAY_RELEASE_MOUNT="-v ${HOME}/.liferay/release:/release"

	if [ -d document_library ]; then
		LIFERAY_RELEASE_MOUNT="-v ${PWD}/document_library:/opt/liferay/data/document_library"
	elif [ -d data/document_library ]; then
		LIFERAY_RELEASE_MOUNT="-v ${PWD}/data/document_library:/opt/liferay/data/document_library"
	fi

	if [ "$PWD" == "$HOME" ] || [ "" != "${LIFERAY_HOME_MOUNT}" ]; then
		return 0
	fi

	if [ -f portal-ext.properties ] || [ -d deploy ]; then
		LIFERAY_HOME=${PWD}
		LIFERAY_HOME_MOUNT="-v ${PWD}:/build"
	elif [ -d bundles ]; then
		LIFERAY_HOME="${PWD}/bundles"
		LIFERAY_HOME_MOUNT="-v ${PWD}/bundles:/build"
	elif [ -f app.server.$USER.properties ]; then
		. $(dirname $(dirname ${BASH_SOURCE[0]}))/appserverprops
		LIFERAY_HOME_MOUNT="-v ${LIFERAY_HOME}:/build"
	fi
}

set_container_name() {
	if [ "" != "${CONTAINER_NAME}" ]; then
		return 0
	fi

	if [ "" != "$1" ] && [[ $1 =~ ^[0-9]*$ ]]; then
		CONTAINER_NAME="test$1"
	else
		CONTAINER_NAME="$1"
	fi
}

set_image_name() {
	if [ "" != "${IMAGE_NAME}" ]; then
		return 0
	fi

	if [[ $1 == 6.1.* ]] || [[ $1 == *-6130 ]] || [[ $1 == *-6130.zip ]]; then
		IMAGE_NAME="holatuwol/liferay:openjdk7"
	elif [[ $1 == portal-* ]] || [[ $1 == 6.2.* ]] || [[ $1 == *-6210 ]] || [[ $1 == *-6210.zip ]]; then
		IMAGE_NAME="holatuwol/liferay:openjdk7"
	else
		IMAGE_NAME="holatuwol/liferay:openjdk8"
	fi
}

start_liferay() {
	if [ "" == "${TOMCAT_PORT}" ]; then
		TOMCAT_PORT=$2
	fi

	if [ "" == "${TOMCAT_PORT}" ]; then
		TOMCAT_PORT=$(python $(dirname ${BASH_SOURCE[0]})/getport.py)
	fi

	if [ "" == "${TOMCAT_PORT}" ]; then
		TOMCAT_PORT=8080
	fi

	if [ "" != "$3" ]; then
		set_container_name $3
	else
		set_container_name ${TOMCAT_PORT}
	fi

	remove_container

	if ! create_network; then
		return 1
	fi

	copy_driver

	local INCREMENT=$(expr ${TOMCAT_PORT} '-' 8080)
	local GLOBAL_BIND="$(echo 8009 8080 8443 | tr ' ' '\n' | awk '{ print  "--publish " $1+'${INCREMENT}' ":" $1 }' | xargs)"
	local LOCAL_BIND="$(echo 8000 11311 | tr ' ' '\n' | awk '{ print  "--publish 127.0.0.1:" $1+'${INCREMENT}' ":" $1 }' | xargs)"
	local EXPOSE_ONLY="$(echo 7800 7801 | tr ' ' '\n' | awk '{ print  "--expose " $1 }' | xargs)"

	local MIRRORS=

	if [ "" != "${BRANCH_ARCHIVE_MIRROR}" ]; then
		MIRRORS="${MIRRORS} -e BRANCH_ARCHIVE_MIRROR=${BRANCH_ARCHIVE_MIRROR}"
	fi

	if [ "" != "${LIFERAY_FILES_MIRROR}" ]; then
		MIRRORS="${MIRRORS} -e LIFERAY_FILES_MIRROR=${LIFERAY_FILES_MIRROR}"
	fi

	if [ "" != "${LIFERAY_RELEASES_MIRROR}" ]; then
		MIRRORS="${MIRRORS} -e LIFERAY_RELEASES_MIRROR=${LIFERAY_RELEASES_MIRROR}"
	fi

	if [ "" != "${LICENSE_MIRROR}" ]; then
		MIRRORS="${MIRRORS} -e LICENSE_MIRROR=${LICENSE_MIRROR}"
	fi

	docker run ${GLOBAL_BIND} ${LOCAL_BIND} ${EXPOSE_ONLY} \
		${LIFERAY_HOME_MOUNT} ${LIFERAY_RDBUILD_MOUNT} ${LIFERAY_RELEASE_MOUNT} ${DOCLIB_MOUNT} \
		-e RELEASE_ID=${RELEASE_ID} \
		-e LIFERAY_PASSWORD=${LIFERAY_PASSWORD} \
		-e IS_UPGRADE=${IS_UPGRADE} \
		-e JVM_HEAP_SIZE=${JVM_HEAP_SIZE} \
		${MIRRORS} ${NETWORK_METADATA} ${EXTRA_ARGS} --name ${CONTAINER_NAME} \
		${IMAGE_NAME} $1
}

if [ "" == "${LIFERAY_PASSWORD}" ]; then
	LIFERAY_PASSWORD='test'
fi

set_container_mounts
set_image_name "$1"

echo "Using Docker image ${IMAGE_NAME}"

start_liferay "$1" "$2" "$3"