#!/bin/bash

fixbnd() {
	for file in $(git ls-files modules | grep build.gradle | xargs grep -l 'version: "\['); do
		MODULE_PATH=$(dirname $file)

		sed -i.bak 's/version: "\[[^"]*\"/version: "default"/g' $file
		python "$(dirname $0)/fixbnd.py" "$MODULE_PATH"
		rm "$MODULE_PATH/bnd.bnd"
		mv "$MODULE_PATH/bnd.tmp" "$MODULE_PATH/bnd.bnd"
	done
}

fixbnd