#!/bin/bash

getparent() {
	echo "Detecting parent branch..."

	local PARENTS=$(python "$(dirname "${BASH_SOURCE[0]}")/getparent.py")

	BASE_TAG=$(echo "${PARENTS}" | head -1)
	BASE_BRANCH=$(echo "${PARENTS}" | tail -1)

	if [ "${BASE_TAG}" == "${BASE_BRANCH}" ]; then
		BASE_TAG=
	fi
}

getparent