#!/bin/bash

getparent() {
	local PARENT=$(python "$(dirname "${BASH_SOURCE[0]}")/getparent.py" $@)

	if [ "" == "${PARENT}" ]; then
		return 1
	fi

	if [ "" != "$(git tag | grep -F ${PARENT} | head -1)" ]; then
		BASE_TAG=${PARENT}
		return 0
	fi

	BASE_BRANCH=${PARENT}
}

getparent