#!/bin/bash

dirnames() {
	python $(dirname "${BASH_SOURCE[0]}")/dirnames.py
}

githashtime() {
	python $(dirname ${BASH_SOURCE[0]})/githashtime.py $1
}

setopts() {
	. $(dirname ${BASH_SOURCE[0]})/setopts
}

setopts

HASH=$1

if [ "" == "$1" ]; then
	HASH=$(git log -1 --pretty='%H')
fi

echo "Resetting timestamps to reference hash ${HASH}..."

(
	sed -n '/target name="deploy"/,/\/target/p' ${GIT_ROOT}/build.xml | grep -F 'ant dir' | grep -F 'target="deploy"' | cut -d'"' -f 2
	git ls-files ${GIT_ROOT}/modules | grep -F .lfrbuild-portal | dirnames
) | githashtime ${HASH}