#!/bin/bash

javahome() {
	# Check for a valid operating system

	BASE_JAVA=
	JAVA_VERSION=$1

	if [ ${HOME}/dev/applications ] && [ ! -d /opt/java ] && [ -d /usr/java ] && [ ! -d /usr/lib/jvm ]; then
		echo "Unable to change Java on your operating system"
		return 0
	fi

	# If this is diagnostic, just report JAVA_HOME

	if [ "" == "${1}" ]; then
		if [ "" != "${JAVA_HOME}" ]; then
			echo JAVA_HOME=${JAVA_HOME}

			if [ -f ${JAVA_HOME}/bin/java ]; then
				${JAVA_HOME}/bin/java 2>&1 -version | head -1
				return 0
			fi
		fi

		JAVA_VERSION=8
	fi

	# Remove the existing JAVA_HOME from the path

	if [ "" != "${JAVA_HOME}" ]; then
		export PATH=$(echo ${PATH} | sed -e "s;:${JAVA_HOME}/bin;;g" | sed -e "s;${JAVA_HOME}/bin:;;g")
	fi

	# Check for a valid /etc/alternatives value

	for BASE_JAVA in ${HOME}/dev/applications /opt/java /usr/java /usr/lib/jvm; do
		if [ ! -d ${BASE_JAVA} ]; then
			continue
		fi

		check_javahome

		if [ "" != "${JAVA_ALT_ID}" ]; then
			break
		fi
	done

	# If we still couldn't find it, report that Java could not be found

	if [ "" == "${JAVA_ALT_ID}" ]; then
		echo "Unable to find Java ${JAVA_VERSION}"
		return 1
	fi

	export JAVA_HOME=${JAVA_ALT_ID}

	# Prepend Java to the path

	echo JAVA_HOME=${JAVA_HOME}
	${JAVA_HOME}/bin/java 2>&1 -version | head -1
	export PATH=${JAVA_HOME}/bin:${PATH}
}

check_javahome() {
	JAVA_ALT_ID=

	# Choose the closest matching version

	for folder in $(ls -1 ${BASE_JAVA} | grep -F "jdk1.${JAVA_VERSION}.0" | sort -t'_' -k2nr); do
		if [ ! -f ${BASE_JAVA}/${folder}/bin/java ]; then
			continue
		fi

		JAVA_ALT_ID=${BASE_JAVA}/${folder}
		break
	done

	if [ "" == "${JAVA_ALT_ID}" ]; then
		for folder in $(ls -1 ${BASE_JAVA} | grep -F "jdk-${JAVA_VERSION}.0" | sort -t'_' -k2nr); do
			if [ ! -f ${BASE_JAVA}/${folder}/bin/java ]; then
				continue
			fi

			JAVA_ALT_ID=$BASE_JAVA/${folder}
			break
		done
	fi

	# If we couldn't find one, maybe they installed it through a package manager

	if [ "" == "${JAVA_ALT_ID}" ]; then
		for folder in $(ls -1 ${BASE_JAVA} | grep -F java-${JAVA_VERSION}-oracle); do
			if [ ! -f ${BASE_JAVA}/${folder}/bin/java ]; then
				continue
			fi

			JAVA_ALT_ID=${BASE_JAVA}/${folder}
			break
		done
	fi

	if [ "" == "${JAVA_ALT_ID}" ]; then
		for folder in $(ls -1 ${BASE_JAVA} | grep -F java-${JAVA_VERSION}-openjdk); do
			if [ ! -f ${BASE_JAVA}/${folder}/bin/java ]; then
				continue
			fi

			JAVA_ALT_ID=${BASE_JAVA}/${folder}
			break
		done
	fi

	if [ "" == "${JAVA_ALT_ID}" ]; then
		for folder in $(ls -1 ${BASE_JAVA} | grep -F zulu${JAVA_VERSION}); do
			if [ ! -f ${BASE_JAVA}/${folder}/bin/java ]; then
				continue
			fi

			JAVA_ALT_ID=${BASE_JAVA}/${folder}
			break
		done
	fi
}

javahome $@