#!/bin/bash

dirnames() {
	python $(dirname "${BASH_SOURCE[0]}")/dirnames.py
}

setopts() {
	. $(dirname "${BASH_SOURCE[0]}")/setopts
}

skipmp() {
	if [ -f build.$USER.properties ] && [ "" != "$(grep -F build.include.dirs build.properties)" ]; then
		if [ "" != "$(grep -F build.include.dirs build.$USER.properties)" ]; then
			echo "build.include.dirs has already been set in build.$USER.properties"
			echo "Assuming that you do not want to use skipmp"
			return 0
		fi

		if [ "" != "$(grep -F build.exclude.dirs build.$USER.properties)" ]; then
			echo "build.exclude.dirs has already been set in build.$USER.properties"
			echo "Assuming that you do not want to use skipmp"
			return 0
		fi

		echo "Neither build.include.dirs nor build.exclude.dirs has been set"
		echo "Restricting build to the following applications (app.bnd)"

		if [ -f $HOME/lpkgs.txt ]; then
			cat $HOME/lpkgs.txt | tr '\n' ',' | sed 's/,/, /g'
		else
			echo -en 'Collaboration\nForms and Workflow\nFoundation\nStatic\nWeb Experience' | tr '\n' ',' | sed 's/,/, /g'
		fi
	fi

	echo -en "\n\n"

	git ls-files -v | grep '^h ' | cut -d' ' -f 2 | grep -F '.lfrbuild-portal' | xargs git update-index --no-assume-unchanged
	git status | grep -F deleted | grep -F '.lfrbuild-portal' | cut -d':' -f 2 | xargs git checkout

	if [ -f $HOME/lpkgs.txt ]; then
		BUNDLE_APPS=$(cat $HOME/lpkgs.txt)
	else
		BUNDLE_APPS=$(echo -e 'Collaboration\nForms and Workflow\nFoundation\nStatic\nWeb Experience')
	fi

	cat /dev/null > .excludes

	for file in $(git ls-files modules | grep -F app.bnd); do
		app=$(grep Liferay-Releng-App-Title $file | cut -d' ' -f 3-)
		is_bundled=$(echo "$BUNDLE_APPS" | grep "^\s*${app}\s*\$")

		if [ "" == "$is_bundled" ]; then
			public_app="$(dirname $file)"
			echo $public_app >> .excludes

			private_app="modules/private/$(echo $public_app | cut -d'/' -f 2-)"

			if [ -d $private_app ]; then
				echo $private_app >> .excludes
			fi
		fi
	done

	for file in $(git ls-files modules/private | grep -F .lfrbuild-portal | grep -F -- '-dxp'); do
		public_app=$(echo $file | sed 's@/private/@/@g' | sed 's@-dxp@@g' | dirnames)

		if [ -d $public_app ]; then
			echo $public_app >> .excludes
		fi
	done

	build_gradles=$(git ls-files modules | grep -F build.gradle)

	if [[ 0 -ne $(cat .excludes | wc -l) ]]; then
		cp -f .excludes .excludes_transitive

		old_count=0
		new_count=$(cat .excludes | sort -u | wc -l)

		while [[ $old_count -ne $new_count ]]; do
			old_count=$new_count
			old_excludes=$(cat .excludes_transitive)

			project_dependencies=$(echo "$old_excludes" | sed 's@^modules/private@@g' | sed 's@^modules@@g' | tr '/' ':' | xargs | tr ' ' '|')

			if [ "" != "$project_dependencies" ]; then
				echo -n "$build_gradles" | xargs grep -l "\($project_dependencies\)" | dirnames > .excludes_transitive
			fi

			library_dependencies=$(echo "$old_excludes" | xargs git ls-files | grep -F bnd.bnd | xargs grep Bundle-SymbolicName | grep -vF '{' | cut -d' ' -f 2 | xargs | tr ' ' '|')

			if [ "" != "$library_dependencies" ]; then
				echo -n "$build_gradles" | xargs grep -l "\"\($library_dependencies\)\"" | dirnames >> .excludes_transitive
			fi

			mv .excludes .excludes_old
			cat .excludes_old .excludes_transitive | sort -u > .excludes
			rm .excludes_old

			new_count=$(cat .excludes | wc -l)
		done

		rm -f .excludes_transitive
	fi

	if [[ 0 -ne $(cat .excludes | wc -l) ]]; then
		exclude=$(cat .excludes | xargs git ls-files | grep -F .lfrbuild-portal | sort -u)

		echo "$exclude" | dirnames | awk '{ print "Excluding " $1 }'
		echo "$exclude" | xargs git update-index --assume-unchanged
		echo "$exclude" | xargs rm -f
	fi

	rm -f .excludes
}

setopts

skipmp