#!/bin/bash

dirnames() {
	python $(dirname "${BASH_SOURCE[0]}")/dirnames.py
}

setopts() {
	. $(dirname "${BASH_SOURCE[0]}")/setopts
}

skipmp() {
	if [ -f build.$USER.properties ] && [ "" != "$(grep -F build.include.dirs build.properties)" ]; then
		if [ "" != "$(grep -F build.include.dirs build.$USER.properties)" ]; then
			echo "build.include.dirs has already been set in build.$USER.properties"
			echo "Assuming that you do not want to use skipmp"
			return 0
		fi

		if [ "" != "$(grep -F build.exclude.dirs build.$USER.properties)" ]; then
			echo "build.exclude.dirs has already been set in build.$USER.properties"
			echo "Assuming that you do not want to use skipmp"
			return 0
		fi
	fi

	if [ ! -f build.$USER.properties ] || [ "" != "$(grep -F build.include.dirs build.properties)" ]; then
		echo "Neither build.include.dirs nor build.exclude.dirs has been set"
		echo "Restricting build to the following applications (detected via app.bnd)"

		if [ -f $HOME/lpkgs.txt ]; then
			cat $HOME/lpkgs.txt | tr '\n' ',' | sed 's/,/, /g'
		else
			echo -en 'Collaboration\nForms and Workflow\nFoundation\nStatic\nWeb Experience' | tr '\n' ',' | sed 's/,/, /g'
		fi

		echo -en "\n\n"
	fi

	git ls-files -v | grep '^h ' | cut -d' ' -f 2 | grep -F '.lfrbuild-portal' | xargs git update-index --no-assume-unchanged
	git status | grep -F deleted | grep -F '.lfrbuild-portal' | cut -d':' -f 2 | xargs git checkout

	if [ -f $HOME/lpkgs.txt ]; then
		BUNDLE_APPS=$(cat $HOME/lpkgs.txt)
	else
		BUNDLE_APPS=$(echo -e 'Collaboration\nForms and Workflow\nFoundation\nStatic\nWeb Experience')
	fi

	cat /dev/null > .excludes

	for file in $(git ls-files modules | grep -F app.bnd); do
		app=$(grep Liferay-Releng-App-Title $file | cut -d' ' -f 3-)
		is_bundled=$(echo "$BUNDLE_APPS" | grep "^\s*${app}\s*\$")

		if [ "" == "$is_bundled" ]; then
			public_app="$(dirname $file)"
			echo $public_app >> .excludes

			private_app="modules/private/$(echo $public_app | cut -d'/' -f 2-)"

			if [ -d $private_app ]; then
				echo $private_app >> .excludes
			fi
		fi
	done

	for file in $(git ls-files modules/private | grep -F .lfrbuild-portal | grep -F -- '-dxp'); do
		public_app=$(echo $file | sed 's@/private/@/@g' | sed 's@-dxp@@g' | dirnames)

		if [ -d $public_app ]; then
			echo $public_app >> .excludes
		fi
	done

	if [[ 0 -ne $(cat .excludes | wc -l) ]]; then
		transitiveexcludes

		exclude=$(cat .excludes | xargs git ls-files | grep -F .lfrbuild-portal | sort -u)

		echo "$exclude" | dirnames | awk '{ print "Excluding " $1 }'
		echo "$exclude" | xargs git update-index --assume-unchanged
		echo "$exclude" | xargs rm -f
	fi

	rm -f .excludes
}

transitiveexcludes() {
	if [[ 0 -eq $(cat .excludes | wc -l) ]]; then
		return 0
	fi

	cp -f .excludes .excludes_transitive

	old_count=0
	new_count=$(cat .excludes | sort -u | wc -l)

	git ls-files modules | grep -vF '/src/' > .redeploy/lsfiles.txt
	cat .redeploy/lsfiles.txt | grep -F '/build.gradle' > .redeploy/gradle_list.txt

	git ls-files modules | grep -vF '/src/' | grep -F '/bnd.bnd' | xargs grep -F Bundle-SymbolicName | \
		grep -vF '{' | sed 's/Bundle-SymbolicName: //g' > .redeploy/bnd_list.txt

	while [[ $old_count -ne $new_count ]]; do
		old_count=$new_count
		old_files=$(cat .excludes_transitive)

		project_dependencies=$(echo "$old_files" | sed 's@^modules/private@@g' | sed 's@^modules@@g' | tr '/' ':' | tr '\n' ' ' | tr -d '\r' | sed 's/ /\\|/g')

		cat /dev/null > .excludes_transitive

		if [ "" != "$project_dependencies" ]; then
			cat .redeploy/gradle_list.txt | xargs grep -l "project(\"\($project_dependencies\)\")" | dirnames >> .excludes_transitive
		fi

		app_folders=$(echo "$old_files" | xargs | sed 's/ /\\|/g')
		library_dependencies=$(grep "\(${app_folders}\)" .redeploy/bnd_list.txt | cut -d ':' -f 2 | xargs | sed 's/ /\\|/g')

		if [ "" != "$library_dependencies" ]; then
			cat .redeploy/gradle_list.txt | xargs grep -l "\"\($library_dependencies\)\"" | dirnames >> .excludes_transitive
		fi

		mv .excludes .excludes_old
		cat .excludes_old .excludes_transitive | sort -u > .excludes
		rm .excludes_old

		new_count=$(cat .excludes | wc -l)
	done

	rm -f .excludes_transitive
}

setopts

skipmp