#!/bin/bash

mkdir -p .redeploy

if [ ! -f .redeploy/sourcetrie.pickle ]; then
	git ls-files | grep '/\(bnd.bnd\|package.json\)$' | grep -vF '/src/' > .redeploy/sourcetrie.txt
	echo 'portal-web/build.xml' >> .redeploy/sourcetrie.txt
	python $(dirname "${BASH_SOURCE[0]}")/sourcetrie.py
fi