#!/bin/bash

unzipportaljar() {
	local JAR_PATH=

	# find the JAR in ROOT/WEB-INF/lib or lib/ext

	if [ -f $LIFERAY_HOME/$TOMCAT_FOLDER/webapps/ROOT/WEB-INF/lib/$1.jar ]; then
		JAR_PATH=$LIFERAY_HOME/$TOMCAT_FOLDER/webapps/ROOT/WEB-INF/lib/$1.jar
	elif [ -f $LIFERAY_HOME/$TOMCAT_FOLDER/lib/ext/$1.jar ]; then
		JAR_PATH=$LIFERAY_HOME/$TOMCAT_FOLDER/lib/ext/$1.jar
	else
		return 1
	fi

	cp -f ${JAR_PATH} $1

	# check to see if the jar is out of date

	local old_timestamp=

	if [ -d $1/classes ]; then
		old_timestamp=$(perl -MPOSIX -e 'print POSIX::strftime "%Y%m%d%H%M.%S", localtime((stat $ARGV[0])[9])' "$1/classes")
	fi

	local new_timestamp=$(perl -MPOSIX -e 'print POSIX::strftime "%Y%m%d%H%M.%S", localtime((stat $ARGV[0])[9])' "$JAR_PATH")

	if [ "$old_timestamp" == "$new_timestamp" ]; then
		return 0
	fi

	rm -rf $1/classes
	mkdir -p $1/classes

	pushd $1/classes > /dev/null
	unzip -fqq "${JAR_PATH}"
	popd > /dev/null

	rm $1/$1.jar

	touch -t $new_timestamp "$1/classes"
}

if [ "" != "$1" ]; then
	unzipportaljar $1
fi