#!/bin/bash

unzipportaljar() {
	if [ -d $1/classes ] && [ -f $1/$1.jar ]; then
		return 0
	fi

	local JAR_PATH=

	# find the JAR in ROOT/WEB-INF/lib or lib/ext

	if [ -f ${CATALINA_HOME}/webapps/ROOT/WEB-INF/lib/$1.jar ]; then
		JAR_PATH=${CATALINA_HOME}/webapps/ROOT/WEB-INF/lib/$1.jar
	elif [ -f ${CATALINA_HOME}/lib/ext/$1.jar ]; then
		JAR_PATH=${CATALINA_HOME}/lib/ext/$1.jar
	else
		return 1
	fi

	cp -f ${JAR_PATH} $1

	# check to see if the jar is out of date

	rm -rf $1/classes
	mkdir $1/classes

	pushd $1/classes > /dev/null
	unzip -oqq ../$1.jar
	popd > /dev/null
}

if [ "" != "$1" ]; then
	unzipportaljar $1
fi