#!/bin/bash

SCRIPT_FOLDER="$(dirname $BASH_SOURCE[0])"

dirnames() {
	python $(dirname "${BASH_SOURCE[0]}")/dirnames.py
}

getmodulepath() {
	grep -F $1 ${GIT_ROOT}/.redeploy/bnd_list.txt > ${GIT_ROOT}/.redeploy/bndmatches.txt

	# search the bnds for the symbolic name

	if [[ 0 -eq $(cat ${GIT_ROOT}/.redeploy/bndmatches.txt | grep -c '^') ]]; then
		echo "Could not find Bundle-SymbolicName $1"
		return 1
	fi

	# at this point, we know we have at least a partial match
	# now to find out if there is an exact guess we can make

	local BND=$(cat ${GIT_ROOT}/.redeploy/bndmatches.txt | cut -d':' -f 1)

	if [[ 1 -eq $(echo "$BND" | grep -c '^') ]]; then
		MODULE_PATH=$(dirname $BND)
		return 0
	fi

	BND=$(grep -F "$1" ${GIT_ROOT}/.redeploy/bndmatches.txt | cut -d':' -f 1)

	if [ "" != "$BND" ] && [[ 1 -eq $(echo "$BND" | grep -c '^') ]]; then
		MODULE_PATH=$(dirname $BND)
		return 0
	fi

	BND=$(grep -F "${1}/bnd.bnd" ${GIT_ROOT}/.redeploy/bndmatches.txt | cut -d':' -f 1)

	if [ "" != "$BND" ] && [[ 1 -eq $(echo "$BND" | grep -c '^') ]]; then
		MODULE_PATH=$(dirname $BND)
		return 0
	fi

	# no exact guesses possible, so report that it is ambiguous

	echo "$1 is ambiguous:"
	cat ${GIT_ROOT}/.redeploy/bndmatches.txt | cut -d':' -f 2
	return 1
}

unziposgijar() {
	# generate a cache that maps between the bundle symbolic name and a module path

	mkdir -p ${GIT_ROOT}/.redeploy

	if [ ! -f ${GIT_ROOT}/.redeploy/bnd_list.txt ]; then
		git ls-files modules | grep -vF '/src/' | grep -F '/bnd.bnd' | grep -vF -- '-test/' | xargs grep -F Bundle-SymbolicName | \
			grep -vF '{' | sed 's/Bundle-SymbolicName: //g' > ${GIT_ROOT}/.redeploy/bnd_list.txt
	fi

	local BASE_PATH=
	local JAR_PATH=
	local BUNDLE_SYMBOLICNAME=
	local MODULE_PATH=

	if [ -f $1 ]; then
		BASE_PATH=$(dirname $1)
		JAR_PATH=$1

		BUNDLE_SYMBOLICNAME=$(basename $JAR_PATH | sed 's/.jar$//g')
		MODULE_PATH=$(grep ":${BUNDLE_SYMBOLICNAME}$" ${GIT_ROOT}/.redeploy/bnd_list.txt | cut -d':' -f 1 | dirnames)
	elif [ -d $1 ] && [ -f $1/bnd.bnd ]; then
		BUNDLE_SYMBOLICNAME=$(grep -F 'Bundle-SymbolicName' $1/bnd.bnd | cut -d' ' -f 2)
		MODULE_PATH=$1

		if [ -d $LIFERAY_HOME/osgi ]; then
			JAR_PATH=$(find $LIFERAY_HOME/osgi -name ${BUNDLE_SYMBOLICNAME}.jar)
		fi

		if [ "" == "${JAR_PATH}" ] && [ -d $CATALINA_HOME/lib/ext ]; then
			JAR_PATH=$(find $CATALINA_HOME/lib/ext -name ${BUNDLE_SYMBOLICNAME}.jar)
		fi

		if [ "" == "${JAR_PATH}" ] && [ -d $CATALINA_HOME/webapps/ROOT/WEB-INF/lib ]; then
			JAR_PATH=$(find $CATALINA_HOME/webapps/ROOT/WEB-INF/lib -name ${BUNDLE_SYMBOLICNAME}.jar)
		fi

		if [ "" != "$JAR_PATH" ]; then
			BASE_PATH=$(dirname $JAR_PATH)
		fi
	elif getmodulepath $1; then
		BUNDLE_SYMBOLICNAME=$(grep -F 'Bundle-SymbolicName' $MODULE_PATH/bnd.bnd | cut -d' ' -f 2)

		if [ -d $LIFERAY_HOME/osgi ]; then
			JAR_PATH=$(find $LIFERAY_HOME/osgi -name $BUNDLE_SYMBOLICNAME.jar)
		fi

		if [ "" == "${JAR_PATH}" ] && [ -d $CATALINA_HOME/lib/ext ]; then
			JAR_PATH=$(find $CATALINA_HOME/lib/ext -name ${BUNDLE_SYMBOLICNAME}.jar)
		fi

		if [ "" != "$JAR_PATH" ]; then
			BASE_PATH=$(dirname $JAR_PATH)
		fi
	else
		return 1
	fi

	# check to see if a matching bnd.bnd exists

	if [ "" == "$MODULE_PATH" ] || [ "" == "$JAR_PATH" ]; then
		return 1
	fi

	# add a rebel.xml to the module jar if we see a .jrebel folder

	if [ -d $HOME/.jrebel ]; then
		local RESOURCE_PATH="$MODULE_PATH/src/main/resources"

		mkdir -p $RESOURCE_PATH

		if [ -d "$RESOURCE_PATH/META-INF/resources" ]; then
			cp -f "$SCRIPT_FOLDER/jrebel-web.xml" "$RESOURCE_PATH/rebel.xml"
		else
			cp -f "$SCRIPT_FOLDER/jrebel.xml" "$RESOURCE_PATH/rebel.xml"
		fi

		sed -i.bak "s@MODULE_CLASSES@${PWD}/${MODULE_PATH}/classes@g" "$RESOURCE_PATH/rebel.xml"
		sed -i.bak "s@MODULE_RESOURCES@${PWD}/${RESOURCE_PATH}/META-INF/resources@g" "$RESOURCE_PATH/rebel.xml"

		rm -f "$RESOURCE_PATH/rebel.xml.bak"

		zip -ujqq "${JAR_PATH}" "${RESOURCE_PATH}/rebel.xml"
	fi

	# unzip the JAR to the classes folder

	if [ ! -d ${MODULE_PATH}/classes ]; then
		rm -rf $MODULE_PATH/classes
		mkdir -p $MODULE_PATH/classes

		pushd $MODULE_PATH/classes > /dev/null
		unzip -qq "${JAR_PATH}"
		popd > /dev/null
	fi

	if [ -f $MODULE_PATH/.lfrbuild-portal-pre ] && [ ! -f tmp/lib-pre/${BUNDLE_SYMBOLICNAME}.jar ]; then
		mkdir -p tmp/lib-pre
		cp ${JAR_PATH} tmp/lib-pre/
	fi
}

if [ "" != "$1" ]; then
	unziposgijar $1
fi