#!/bin/bash

gitcd() {

	. "$(dirname "${BASH_SOURCE[0]}")/gitfind" $@

	if [ "" != "$FOLDER" ]; then
		builtin cd "$FOLDER"
		pwd
		return 0
	fi

	echo "Falling back to builtin cd"
	builtin cd $@
}

gitcd $@