#!/bin/bash

gitcdb() {
	if [ "" == "$1" ]; then
		echo 'Please specify a Bundle-SymbolicName to locate'
		return 1
	fi

	# git ls-files wants a relative path, so let's generate it

	local ROOT_FOLDER=$(python -c "from __future__ import print_function; import os.path; print(os.path.relpath('$GIT_ROOT', '$PWD'))")

	# use git ls-files to find bnd.bnd files, then use grep -l to list matching files

	local BND=$(git ls-files $ROOT_FOLDER | grep bnd.bnd | xargs grep -l ": .*${1}$")

	if [ "" == "$BND" ]; then
		echo "Could not find Bundle-SymbolicName $1"
		return 1
	fi

	builtin cd $(dirname $BND)
	pwd
}

. "$(dirname "${BASH_SOURCE[0]}")/../setopts"

if [ "" != "$GIT_ROOT" ]; then
	gitcdb $@
fi