#!/bin/bash

. "$(dirname ${BASH_SOURCE[0]})/common"

restorebackup() {
	echo 'Backup creation not supported!'
}

startdatabase() {
	if docker inspect ${CONTAINER_NAME} 1>/dev/null 2>/dev/null; then
		echo "Using existing container ${CONTAINER_NAME}"
		docker start ${CONTAINER_NAME}
		return 0
	fi

	docker run --name ${CONTAINER_NAME} \
		-e 'MYSQL_ALLOW_EMPTY_PASSWORD=yes' -e 'MYSQL_USER=lportal' -e 'MYSQL_PASSWORD=lportal' -e 'MYSQL_DATABASE=lportal' \
		--health-cmd='mysqladmin ping --silent' \
		--detach -p 3307:3306 mysql:${MYSQL_VERSION} \
		--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

	echo "
[mysqld]
character-set-server  = utf8mb4
collation-server      = utf8mb4_unicode_ci
" > runtime.cnf

	docker cp runtime.cnf ${CONTAINER_NAME}:/etc/mysql/conf.d/
	rm runtime.cnf

	docker restart ${CONTAINER_NAME}

	waitfor_database

	echo "create schema lportal;" | \
		docker exec -i ${CONTAINER_NAME} /bin/bash -c 'mysql'

	echo "create user lportal identified by 'lportal';" | \
		docker exec -i ${CONTAINER_NAME} /bin/bash -c 'mysql'

	echo "grant all on lportal.* to 'lportal'@'%';" | \
		docker exec -i ${CONTAINER_NAME} /bin/bash -c 'mysql'
}

updateprops() {
	if [ "" == "${DB_HOST_NAME}" ]; then
		DB_HOST_NAME=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${CONTAINER_NAME})
		echo "MySQL database is started with IP address ${DB_HOST_NAME}"
	fi

	echo "Updating ${LIFERAY_HOME}/portal-ext.properties with database connection information"

	if [ -f ${LIFERAY_HOME}/portal-ext.properties ]; then
		if [ "" != "$(grep -F ${DB_HOST_NAME} ${LIFERAY_HOME}/portal-ext.properties | grep -vF '#')" ]; then
			return 0
		fi

		sed -i.bak 's/^jdbc.default/#jdbc.default/g' ${LIFERAY_HOME}/portal-ext.properties
	fi

	echo '' >> ${LIFERAY_HOME}/portal-ext.properties

	if [ -f portal-impl/src/portal.properties ]; then
		grep -F mysql portal-impl/src/portal.properties | grep -F jdbc.default.driverClassName | sed 's/ *#//g' >> ${LIFERAY_HOME}/portal-ext.properties
	else
		echo "jdbc.default.driverClassName=com.mysql.jdbc.Driver" >> ${LIFERAY_HOME}/portal-ext.properties
	fi

	echo "
jdbc.default.url=jdbc:mysql://${DB_HOST_NAME}/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useUnicode=true&serverTimezone=GMT
jdbc.default.username=lportal
jdbc.default.password=lportal
" >> ${LIFERAY_HOME}/portal-ext.properties
}

waitfor_database() {
	echo 'Waiting for database startup to complete...'

	local HEALTH=$(docker inspect --format "{{json .State.Health.Status }}" ${CONTAINER_NAME} | cut -d'"' -f 2)

	while [ "healthy" != "$HEALTH" ]; do
		sleep 1
		HEALTH=$(docker inspect --format "{{json .State.Health.Status }}" ${CONTAINER_NAME} | cut -d'"' -f 2)
	done

	echo 'Database startup complete!'
}

DB_TYPE='mysql'

if [ "" == "${MYSQL_VERSION}" ]; then
	MYSQL_VERSION='5.7.38-oracle'
fi

runcontainer $@