#!/bin/bash

appserverprops() {
	. $(dirname ${BASH_SOURCE[0]})/../appserverprops
}

getparent() {
	. $(dirname ${BASH_SOURCE[0]})/../getparent
}

startdatabase() {
	if docker inspect ${CONTAINER_NAME} 2>&1 > /dev/null; then
		echo "Using existing container ${CONTAINER_NAME}"
		docker start ${CONTAINER_NAME}
		return 0
	fi

	docker run --name ${CONTAINER_NAME} \
		-e 'MYSQL_ALLOW_EMPTY_PASSWORD=yes' -e 'MYSQL_USER=lportal' -e 'MYSQL_PASSWORD=lportal' -e 'MYSQL_DATABASE=lportal' \
		--health-cmd='mysqladmin ping --silent' \
		--detach --expose 3306 mysql:${MYSQL_VERSION} \
		--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

	local INNODB_FILE_FORMAT='Barracuda'

	if [ "5.5" == "${MYSQL_VERSION}" ]; then
		INNODB_FILE_FORMAT='Antelope'
	fi

	echo "
[mysqld]
innodb-file-format    = ${INNODB_FILE_FORMAT}
innodb-file-per-table
innodb-large-prefix

character-set-server  = utf8mb4
collation-server      = utf8mb4_unicode_ci
" > runtime.cnf

	docker cp runtime.cnf ${CONTAINER_NAME}:/etc/mysql/conf.d/
	rm runtime.cnf

	docker restart ${CONTAINER_NAME}
}

updateprops() {
	local IP_ADDRESS=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${CONTAINER_NAME})
	echo "MySQL database is started with IP address ${IP_ADDRESS}"

	echo "Updating ${LIFERAY_HOME}/portal-ext.properties with database connection information"

	if [ -f ${LIFERAY_HOME}/portal-ext.properties ]; then
		if [ "" != "$(grep -F ${IP_ADDRESS} ${LIFERAY_HOME}/portal-ext.properties | grep -vF '#')" ]; then
			return 0
		fi

		sed -i.bak 's/^jdbc.default/#jdbc.default/g' ${LIFERAY_HOME}/portal-ext.properties
	fi

	echo "
jdbc.default.driverClassName=com.mysql.jdbc.Driver
jdbc.default.url=jdbc:mysql://${IP_ADDRESS}/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&useFastDateParsing=false&useUnicode=true
jdbc.default.username=lportal
jdbc.default.password=lportal
" >> ${LIFERAY_HOME}/portal-ext.properties
}

waitfor_database() {
	echo 'Waiting for database startup to complete...'

	local HEALTH=$(docker inspect --format "{{json .State.Health.Status }}" ${CONTAINER_NAME} | cut -d'"' -f 2)

	while [ "healthy" != "$HEALTH" ]; do
		sleep 1
		HEALTH=$(docker inspect --format "{{json .State.Health.Status }}" ${CONTAINER_NAME} | cut -d'"' -f 2)
	done

	HEALTH=$(docker logs ${CONTAINER_NAME} 2>&1 | grep -F Ready)

	while [ "" == "$HEALTH" ]; do
		sleep 1
		HEALTH=$(docker logs ${CONTAINER_NAME} 2>&1 | grep -F Ready)
	done

	echo 'Database startup complete!'
}

appserverprops

if [ "" == "${LIFERAY_HOME}" ]; then
	echo 'Please either define LIFERAY_HOME or navigate to a portal source folder'
	exit 1
fi

getparent

if [ "ee-6.0.x" == "${BASE_BRANCH}" ] || [ "ee-6.1.x" == "${BASE_BRANCH}" ]; then
	MYSQL_VERSION='5.5'
elif [ "ee-6.2.x" == "${BASE_BRANCH}" ]; then
	MYSQL_VERSION='5.6'
else
	MYSQL_VERSION='5.7'
fi

if [ "" == "$1" ]; then
	CONTAINER_NAME=$(git rev-parse --abbrev-ref HEAD)

	if [ "" == "${CONTAINER_NAME}" ]; then
		echo 'Unable to determine branch name from detached head'
		exit 1
	fi
else
	CONTAINER_NAME=$1
fi

startdatabase && updateprops && waitfor_database