#!/bin/bash

csvmanifest() {
	if [ ! -f "$2" ]; then
		echo $2 could not be found
		return 1
	fi

	local MANIFEST="cat $2"

	if [[ $2 == *.jar ]]; then
		MANIFEST="unzip -p $2 META-INF/MANIFEST.MF"
	fi

	${MANIFEST} | sed -n "/${1}-Package/,/^[^ ]/p" | sed '$d' | sed "1s/${1}-Package://" | tr -d '[:space:]' | \
		sed 's/",/"\n/g' | sed 's/;uses:="[^"]*"//g' | sed 's/;version=/,/g' | sed 's/,\([^"0-9]\)/\n\1/g' | \
		sort | tee "${2}.csv"
}

csvmanifest $@