#!/bin/bash

print_version_gradle() {
	local VERSION=$(git show ${1}:${3}/build.gradle | grep -F 'String '${4} | cut -d'"' -f 2)
	echo '    "'${2}'": "'${VERSION}'",'
}

print_version_package() {
	local VERSION=$(git show ${1}:${3}/package.json | jq '.dependencies["'${4}'"]' | cut -d'"' -f 2)
	echo '    "'${2}'": "'${VERSION}'",'
}

print_version_packagelock() {
	local VERSION=$(git show ${1}:${3}/package-lock.json | jq '.dependencies["'${4}'"].version' | cut -d'"' -f 2)
	echo '    "'${2}'": "'${VERSION}'",'
}

print_version_shrinkwrap() {
	local VERSION=$(git show ${1}:${3}/npm-shrinkwrap.json | jq '.dependencies["'${4}'"].version' | cut -d'"' -f 2)
	echo '    "'${2}'": "'${VERSION}'",'
}

print_version_yarnlock() {
	local VERSION=$(git show ${1}:modules/yarn.lock | grep 'https://[^/]*/'${3}'/' | grep resolved | grep -o '/'${3}'-[0-9]*\.[0-9]*\.[^\.]*\.tgz' | grep -o '[0-9]*\.[0-9]*\.[^\.]*')
	echo '    "'${2}'": "'${VERSION}'",'
}

pushd ${PORTAL_SOURCE_ROOT} > /dev/null

MAX_70_CE=$(git tag | grep -o '^7.0.[0-9]-ga[0-9]$' | wc -l)
MAX_70_EE=$(git tag | grep -o '^fix-pack-de-[0-9]*-7010$' | wc -l)
MAX_71_CE=$(git tag | grep -o '^7.1.[0-9]-ga[0-9]$' | wc -l)
MAX_71_EE=$(git tag | grep -o '^fix-pack-dxp-[0-9]*-7110$' | wc -l)
MAX_72_CE=$(git tag | grep -o '^7.2.[0-9]-ga[0-9]$' | wc -l)
MAX_72_EE=$(git tag | grep -o '^fix-pack-dxp-[0-9]*-7210$' | wc -l)
MAX_73_CE=$(git tag | grep -o '^7.3.[0-9]-ga[0-9]$' | wc -l)
MAX_73_EE=$(git tag | grep -o '^fix-pack-dxp-[0-9]*-7310$' | wc -l)
MAX_74_CE=$(git tag | grep -o '^7.4.[0-9]-ga[0-9]$' | wc -l)
MAX_74_EE=$(git tag | grep -o '^fix-pack-dxp-[0-9]*-7413$' | wc -l)

echo '['

(
	echo '  {'
	echo '    "name": "alloy-ui",'
	echo '    "github": "https://github.com/liferay/alloy-ui",'
	echo '    "tag": "${1}",'

	# Liferay 7.0

	print_version_gradle fix-pack-base-7010 7010-base modules/apps/foundation/frontend-js/frontend-js-web alloyUIVersion

	for i in $(seq 1 4); do
		print_version_gradle 7.0.$((i - 1))-ga${i} 700$((i - 1))-ga${i} modules/apps/foundation/frontend-js/frontend-js-web alloyUIVersion
	done

	for i in $(seq 5 ${MAX_70_CE}); do
		print_version_gradle 7.0.$((i - 1))-ga${i} 700$((i - 1))-ga${i} modules/apps/foundation/frontend-js/frontend-js-aui-web alloyUIVersion
	done

	for i in $(seq 1 27); do
		print_version_gradle fix-pack-de-${i}-7010 7010-de-$(printf "%02d\n" ${i}) modules/apps/foundation/frontend-js/frontend-js-web alloyUIVersion
	done

	for i in $(seq 28 ${MAX_70_EE}); do
		print_version_gradle fix-pack-de-${i}-7010 7010-de-$(printf "%02d\n" ${i}) modules/apps/foundation/frontend-js/frontend-js-aui-web alloyUIVersion
	done

	# Liferay 7.1

	for i in $(seq 1 ${MAX_71_CE}); do
		print_version_gradle 7.1.$((i - 1))-ga${i} 710$((i - 1))-ga${i} modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion
	done

	print_version_gradle fix-pack-base-7110 7110-base modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion

	for i in $(seq 1 ${MAX_71_EE}); do
		print_version_gradle fix-pack-dxp-${i}-7110 7110-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion
	done

	# Liferay 7.2

	for i in $(seq 1 ${MAX_72_CE}); do
		print_version_gradle 7.2.$((i - 1))-ga${i} 720$((i - 1))-ga${i} modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion
	done

	print_version_gradle fix-pack-base-7210 7210-base modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion

	for i in $(seq 1 ${MAX_72_EE}); do
		print_version_gradle fix-pack-dxp-${i}-7210 7210-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion
	done

	# Liferay 7.3

	for i in $(seq 1 ${MAX_73_CE}); do
		print_version_gradle 7.3.$((i - 1))-ga${i} 730$((i - 1))-ga${i} modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion
	done

	print_version_gradle fix-pack-base-7310 7310-base modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion

	for i in $(seq 1 ${MAX_73_EE}); do
		print_version_gradle fix-pack-dxp-${i}-7310 7310-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion
	done

	# Liferay 7.4

	for i in $(seq 1 ${MAX_74_CE}); do
		print_version_gradle 7.4.$((i - 1))-ga${i} 740$((i - 1))-ga${i} modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion
	done

	print_version_gradle fix-pack-base-7413 7413-base modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion

	for i in $(seq 1 ${MAX_74_EE}); do
		print_version_gradle fix-pack-dxp-${i}-7413 7413-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-js/frontend-js-aui-web alloyUIVersion
	done
) | sed '$s/,//g'

echo '  },'

(
	echo '  {'
	echo '    "name": "alloyeditor",'
	echo '    "github": "https://github.com/liferay/alloy-editor",'
	echo '    "tag": "v${1}",'

	# Liferay 7.0

	for i in $(seq 1 3); do
		print_version_gradle 7.0.$((i - 1))-ga${i} 700$((i - 1))-ga${i} modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web alloyEditorVersion
	done

	for i in $(seq 4 6); do
		print_version_shrinkwrap 7.0.$((i - 1))-ga${i} 700$((i - 1))-ga${i} modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web alloyeditor
	done

	for i in $(seq 7 ${MAX_70_CE}); do
		print_version_packagelock 7.0.$((i - 1))-ga${i} 700$((i - 1))-ga${i} modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web alloyeditor
	done

	print_version_gradle fix-pack-base-7010 7010-base modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web alloyEditorVersion

	for i in $(seq 1 8); do
		print_version_gradle fix-pack-de-${i}-7010 7010-de-$(printf "%02d\n" ${i}) modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web alloyEditorVersion
	done

	for i in $(seq 9 45); do
		print_version_shrinkwrap fix-pack-de-${i}-7010 7010-de-$(printf "%02d\n" ${i}) modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web alloyeditor
	done

	for i in $(seq 46 ${MAX_70_EE}); do
		print_version_packagelock fix-pack-de-${i}-7010 7010-de-$(printf "%02d\n" ${i}) modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web alloyeditor
	done

	# Liferay 7.1

	for i in $(seq 1 ${MAX_71_CE}); do
		print_version_packagelock 7.1.$((i - 1))-ga${i} 710$((i - 1))-ga${i} modules/apps/frontend-editor/frontend-editor-alloyeditor-web alloyeditor
	done

	print_version_packagelock fix-pack-base-7110 7110-base modules/apps/frontend-editor/frontend-editor-alloyeditor-web alloyeditor

	for i in $(seq 1 12); do
		print_version_packagelock fix-pack-dxp-${i}-7110 7110-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-editor/frontend-editor-alloyeditor-web alloyeditor
	done

	for i in $(seq 13 ${MAX_71_EE}); do
		print_version_yarnlock fix-pack-dxp-${i}-7110 7110-dxp-$(printf "%02d\n" ${i}) alloyeditor
	done

	# Liferay 7.2

	for i in $(seq 1 ${MAX_72_CE}); do
		print_version_yarnlock 7.2.$((i - 1))-ga${i} 720$((i - 1))-ga${i} alloyeditor
	done

	print_version_yarnlock fix-pack-base-7210 7210-base alloyeditor

	for i in $(seq 1 ${MAX_72_EE}); do
		print_version_yarnlock fix-pack-dxp-${i}-7210 7210-dxp-$(printf "%02d\n" ${i}) alloyeditor
	done

	# Liferay 7.3

	for i in $(seq 1 ${MAX_73_CE}); do
		print_version_yarnlock 7.3.$((i - 1))-ga${i} 730$((i - 1))-ga${i} alloyeditor
	done

	print_version_yarnlock fix-pack-base-7310 7310-base alloyeditor

	for i in $(seq 1 ${MAX_73_EE}); do
		print_version_yarnlock fix-pack-dxp-${i}-7310 7310-dxp-$(printf "%02d\n" ${i}) alloyeditor
	done

	# Liferay 7.4

	for i in $(seq 1 ${MAX_74_CE}); do
		print_version_yarnlock 7.4.$((i - 1))-ga${i} 740$((i - 1))-ga${i} alloyeditor
	done

	print_version_yarnlock fix-pack-base-7413 7413-base alloyeditor

	for i in $(seq 1 ${MAX_74_EE}); do
		print_version_yarnlock fix-pack-dxp-${i}-7413 7413-dxp-$(printf "%02d\n" ${i}) alloyeditor
	done
) | sed '$s/,//g'

echo '  },'

(
	echo '  {'
	echo '    "name": "lexicon-ux",'
	echo '    "github": "https://github.com/liferay/clay",'
	echo '    "tag": "v${1}",'

	# Liferay 7.0

	for i in $(seq 1 ${MAX_70_CE}); do
		print_version_gradle 7.0.$((i - 1))-ga${i} 700$((i - 1))-ga${i} modules/apps/foundation/frontend-js/frontend-js-web lexiconVersion
	done

	print_version_gradle fix-pack-base-7010 7010-base modules/apps/foundation/frontend-js/frontend-js-web lexiconVersion

	for i in $(seq 1 ${MAX_70_EE}); do
		print_version_gradle fix-pack-de-${i}-7010 7010-de-$(printf "%02d\n" ${i}) modules/apps/foundation/frontend-js/frontend-js-web lexiconVersion
	done
) | sed '$s/,//g'

echo '  },'

(
	echo '  {'
	echo '    "name": "clay-css",'
	echo '    "github": "https://github.com/liferay/clay",'
	echo '    "tag": "v${1}",'

	# Liferay 7.1

	for i in $(seq 1 ${MAX_71_CE}); do
		print_version_packagelock 7.1.$((i - 1))-ga${i} 710$((i - 1))-ga${i} modules/apps/frontend-taglib/frontend-taglib-clay clay-component
	done

	print_version_packagelock fix-pack-base-7110 7110-base modules/apps/frontend-taglib/frontend-taglib-clay clay-component

	for i in $(seq 1 12); do
		print_version_packagelock fix-pack-dxp-${i}-7110 7110-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-taglib/frontend-taglib-clay clay-component
	done

	for i in $(seq 13 ${MAX_71_EE}); do
		print_version_yarnlock fix-pack-dxp-${i}-7110 7110-dxp-$(printf "%02d\n" ${i}) clay-css
	done

	# Liferay 7.2

	for i in $(seq 1 ${MAX_72_CE}); do
		print_version_yarnlock 7.2.$((i - 1))-ga${i} 720$((i - 1))-ga${i} clay-css
	done

	print_version_yarnlock fix-pack-base-7210 7210-base clay-css

	for i in $(seq 1 ${MAX_72_EE}); do
		print_version_yarnlock fix-pack-dxp-${i}-7210 7210-dxp-$(printf "%02d\n" ${i}) clay-css
	done

	# Liferay 7.3

	for i in $(seq 1 ${MAX_73_CE}); do
		print_version_yarnlock 7.3.$((i - 1))-ga${i} 730$((i - 1))-ga${i} clay-css
	done

	print_version_yarnlock fix-pack-base-7310 7310-base clay-css

	for i in $(seq 1 ${MAX_73_EE}); do
		print_version_yarnlock fix-pack-dxp-${i}-7310 7310-dxp-$(printf "%02d\n" ${i}) clay-css
	done

	# Liferay 7.4

	for i in $(seq 1 ${MAX_74_CE}); do
		print_version_yarnlock 7.4.$((i - 1))-ga${i} 740$((i - 1))-ga${i} clay-css
	done

	print_version_yarnlock fix-pack-base-7413 7413-base clay-css

	for i in $(seq 1 ${MAX_74_EE}); do
		print_version_yarnlock fix-pack-dxp-${i}-7413 7413-dxp-$(printf "%02d\n" ${i}) clay-css
	done
) | sed '$s/,//g'

echo '  },'

(
	echo '  {'
	echo '    "name": "react",'
	echo '    "github": "https://github.com/facebook/react",'
	echo '    "tag": "v${1}",'

	# Liferay 7.1

	for i in $(seq 16 ${MAX_71_EE}); do
		print_version_package fix-pack-dxp-${i}-7110 7110-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-js/frontend-js-react-web react
	done

	# Liferay 7.2

	for i in $(seq 2 ${MAX_72_CE}); do
		print_version_package 7.2.$((i - 1))-ga${i} 720$((i - 1))-ga${i} modules/apps/frontend-js/frontend-js-react-web react
	done

	for i in $(seq 1 ${MAX_72_EE}); do
		print_version_package fix-pack-dxp-${i}-7210 7210-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-js/frontend-js-react-web react
	done

	# Liferay 7.3

	for i in $(seq 1 ${MAX_73_CE}); do
		print_version_package 7.3.$((i - 1))-ga${i} 730$((i - 1))-ga${i} modules/apps/frontend-js/frontend-js-react-web react
	done

	print_version_package fix-pack-base-7310 7310-base modules/apps/frontend-js/frontend-js-react-web react

	for i in $(seq 1 ${MAX_73_EE}); do
		print_version_package fix-pack-dxp-${i}-7310 7310-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-js/frontend-js-react-web react
	done

	# Liferay 7.4

	for i in $(seq 1 ${MAX_74_CE}); do
		print_version_package 7.4.$((i - 1))-ga${i} 740$((i - 1))-ga${i} modules/apps/frontend-js/frontend-js-react-web react
	done

	print_version_package fix-pack-base-7413 7413-base modules/apps/frontend-js/frontend-js-react-web react

	for i in $(seq 1 ${MAX_74_EE}); do
		print_version_package fix-pack-dxp-${i}-7413 7413-dxp-$(printf "%02d\n" ${i}) modules/apps/frontend-js/frontend-js-react-web react
	done
) | sed '$s/,//g'

echo '  }'

echo ']'

popd > /dev/null