#!/bin/bash

SCRIPT_FOLDER=$(dirname $0)

s3upload() {
	. ${SCRIPT_FOLDER}/s3upload $1
}

if [ -f lsv_fixedin.json ]; then
	mv lsv_fixedin.json lsv_fixedin.json.old
fi

python ${SCRIPT_FOLDER}/lsv_fixedin.py

if [ "" != "${S3_BUCKET}" ]; then
	if [ -f lsv_fixedin.json.old ]; then
		diff lsv_fixedin.json lsv_fixedin.json.old
		if [ "" != "$(diff lsv_fixedin.json lsv_fixedin.json.old)" ]; then
			s3upload lsv_fixedin.json
		fi

		rm -f lsv_fixedin.json.old
	else
		s3upload lsv_fixedin.json
	fi
fi