#!/bin/bash

bundleinfo() {
  version=${1}
  filename=bundleinfo-${2}.txt

  if [ -f ${filename} ]; then
    echo "${filename} has already been generated"
    return 0
  fi

  curl --silent --show-error --fail "https://repository.liferay.com/nexus/content/repositories/liferay-public-releases/com/liferay/portal/release.dxp.bom/${version}/release.dxp.bom-${version}.pom" > pom.xml

  if [ -s pom.xml ]; then
    cat pom.xml | xq -r '.project.dependencyManagement.dependencies.dependency[] | .groupId + "," + .artifactId + "," + .version' > ${filename}
  else
    cat /dev/null > ${filename}
  fi

  rm pom.xml
}

# 7.3 updates

mkdir -p 7.3.x/metadata
pushd 7.3.x/metadata
cat /dev/null > tags.txt

bundleinfo 7.3.10 7310-base
bundleinfo 7.3.10.fp1 7310.u1
bundleinfo 7.3.10.fp2 7310.u2
bundleinfo 7.3.10.3 7310.u3

for tag in $(
  git ls-remote -t git@github.com:liferay/liferay-portal-ee.git | \
    awk '{ print $2 }' | grep "/7.3.10-u[0-9]*$" | \
    sort -V | cut -d'/' -f 3 | tee -a tags.txt
); do

  version="$(echo ${tag} | sed 's/-u/.u/g')"
  filename="$(echo ${tag} | sed 's/\.//g')"

  bundleinfo ${version} ${filename}
done

popd

# 7.4 updates & quarterly releases

mkdir -p 7.4.x/metadata
pushd 7.4.x/metadata
cat /dev/null > tags.txt

for tag in $(
  git ls-remote -t git@github.com:liferay/liferay-portal-ee.git | \
    awk '{ print $2 }' | grep "/7.4.13-u[0-9]*$" | \
    sort -V | cut -d'/' -f 3 | tee -a tags.txt
); do

  version="$(echo ${tag} | sed 's/-u/.u/g')"
  filename="$(echo ${tag} | sed 's/\.//g')"

  bundleinfo ${version} ${filename}
done

for tag in $(
  git ls-remote -t git@github.com:liferay/liferay-portal-ee.git | \
    awk '{ print $2 }' | grep "/[0-9][0-9]*.q[0-9][0-9]*.[0-9][0-9]*$" | \
    sort -V | cut -d'/' -f 3 | tee -a tags.txt
); do

  version="${tag}"
  filename="7413-${tag}"

  bundleinfo ${version} ${filename}
done

popd