#!/bin/bash

SCRIPT_FOLDER=$(dirname $0)

. ${SCRIPT_FOLDER}/packageinfo

if [ "" == "${PACKAGEINFO_ROOT}" ]; then
	PACKAGEINFO_ROOT="${HOME}/dev/packageinfo"
fi

if [ "" == "${PORTAL_SOURCE_ROOT}" ]; then
	PORTAL_SOURCE_ROOT="${HOME}/dev/liferay/master"
fi

s3upload() {
	. ${SCRIPT_FOLDER}/s3upload $1
}

restore_backup() {
	if [ -d ${folder}.x/metadata ]; then
		return
	fi

	metadata_zip="metadata-$(echo ${1} | tr -d '.')x.zip"
	echo "Restoring metadata for ${1} from backup ${metadata_zip}"

	cd ${1}.x
	mkdir metadata
	cd metadata
	aws s3 cp s3://${S3_BUCKET}/${metadata_zip} ${metadata_zip}.gz
	gunzip ${metadata_zip}.gz
	unzip ${metadata_zip}
	rm ${metadata_zip}
	cd ../..
}

update_all() {
	pushd ${PACKAGEINFO_ROOT}

	for folder in ${AVAILABLE_VERSIONS}; do
		restore_backup ${folder}
	done

	popd

	for version in ${AVAILABLE_VERSIONS}; do
		packageinfo_release ${PORTAL_SOURCE_ROOT} ${PACKAGEINFO_ROOT}/${version}.x/metadata ${version} $(echo ${version} | tr -d '.')
	done
}

update_one() {
	OUTPUT_FOLDER=/tmp

	pushd ${PORTAL_SOURCE_ROOT}
	packageinfo_tag $1
	popd
}

generate_json() {
	echo 'Generating JSON files...'

	echo "${AVAILABLE_VERSIONS}" | awk '{ print "'${PACKAGEINFO_ROOT}'/" $1 ".x" }' | xargs python ${SCRIPT_FOLDER}/packageinfojson.py
	echo "${AVAILABLE_VERSIONS}" | awk '{ print "'${PACKAGEINFO_ROOT}'/" $1 ".x" }' | xargs python ${SCRIPT_FOLDER}/requireschemajson.py

	PORTAL_SOURCE_ROOT=${PORTAL_SOURCE_ROOT} ${SCRIPT_FOLDER}/jsversions > dxpjslibrary.json
}

upload_json() {
	if [ "" == "${AWS_PROFILE}" ]; then
		echo 'Please set AWS_PROFILE to upload files'
		return
	fi

	if [ "" == "${S3_BUCKET}" ]; then
		echo 'Please set S3_BUCKET to upload files'
		return
	fi

	for file in dxppackages dxpmodules dxpschemas dxpjslibrary mpmodules; do
		s3upload ${file}.json

		pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null

		s3upload ${file}.html
		s3upload ${file}.js

		popd > /dev/null
	done

	pushd /tmp > /dev/null

	for version in ${AVAILABLE_VERSIONS}; do
		short_version=$(echo "${version}" | tr -d '.')
		rm -f metadata-${short_version}x.zip
		zip -jqqr metadata-${short_version}x.zip ${PACKAGEINFO_ROOT}/${version}.x/metadata
		s3upload metadata-${short_version}x.zip
	done

	popd > /dev/null
}

# Make sure the packageinfo files are up to date

AVAILABLE_VERSIONS="$(find ${PACKAGEINFO_ROOT} -mindepth 1 -maxdepth 1 -type d | sed 's@^.*/@@g' | sort | cut -d'.' -f 1,2)"

if [ "update" == "${1}" ]; then
	if [ "" == "${2}" ]; then
		update_all
		generate_json
		upload_json
	else
		update_one ${2}
	fi
else
	generate_json
	upload_json
fi