#!/bin/bash

SCRIPT_FOLDER=$(dirname $0)

s3upload() {
	. ${SCRIPT_FOLDER}/s3upload $1
}

if [ "" != "${PACKAGEINFO_ROOT}" ]; then
	PORTAL_SOURCE_ROOT_70=${PACKAGEINFO_ROOT}/7.0.x/portal
	PORTAL_SOURCE_ROOT_71=${PACKAGEINFO_ROOT}/7.1.x/portal
	PORTAL_SOURCE_ROOT_72=${PACKAGEINFO_ROOT}/7.2.x/portal
	PORTAL_SOURCE_ROOT_73=${PACKAGEINFO_ROOT}/7.3.x/portal
fi

# Make sure the packageinfo files are up to date

if [ "update" == "${1}" ]; then
	. ${SCRIPT_FOLDER}/packageinfo

	if [ "" == "${2}" ]; then
		packageinfo_release ${PORTAL_SOURCE_ROOT_70} 7.0 70
		packageinfo_release ${PORTAL_SOURCE_ROOT_71} 7.1 71
		packageinfo_release ${PORTAL_SOURCE_ROOT_72} 7.2 72
		packageinfo_release ${PORTAL_SOURCE_ROOT_73} 7.3 73
	else
		. $(dirname ${BASH_SOURCE[0]})/../setopts
		packageinfo_tag $2
	fi
fi

# Generate the JSON files

python ${SCRIPT_FOLDER}/packageinfojson.py $(dirname $PORTAL_SOURCE_ROOT_70) $(dirname $PORTAL_SOURCE_ROOT_71) $(dirname $PORTAL_SOURCE_ROOT_72) $(dirname $PORTAL_SOURCE_ROOT_73)
python ${SCRIPT_FOLDER}/requireschemajson.py $(dirname $PORTAL_SOURCE_ROOT_70) $(dirname $PORTAL_SOURCE_ROOT_71) $(dirname $PORTAL_SOURCE_ROOT_72) $(dirname $PORTAL_SOURCE_ROOT_73)

PORTAL_SOURCE_ROOT=${PORTAL_SOURCE_ROOT_70} ${SCRIPT_FOLDER}/jsversions > dxpjslibrary.json

# Upload the files to the designated bucket

if [ "" != "${S3_BUCKET}" ]; then
	for file in dxppackages dxpmodules dxpschemas dxpjslibrary mpmodules; do
		s3upload ${file}.json

		pushd $(dirname ${BASH_SOURCE[0]}) > /dev/null

		s3upload ${file}.html
		s3upload ${file}.js

		popd > /dev/null
	done

	cd /tmp

	if [ ! -z "${PORTAL_SOURCE_ROOT_70}" ]; then
		rm -f metadata-70x.zip
		zip -jqqr metadata-70x.zip $(dirname $PORTAL_SOURCE_ROOT_70)/metadata
		s3upload metadata-70x.zip
	fi

	if [ ! -z "${PORTAL_SOURCE_ROOT_71}" ]; then
		rm -f metadata-71x.zip
		zip -jqqr metadata-71x.zip $(dirname $PORTAL_SOURCE_ROOT_71)/metadata
		s3upload metadata-71x.zip
	fi

	if [ ! -z "${PORTAL_SOURCE_ROOT_72}" ]; then
		rm -f metadata-72x.zip
		zip -jqqr metadata-72x.zip $(dirname $PORTAL_SOURCE_ROOT_72)/metadata
		s3upload metadata-72x.zip
	fi

	if [ ! -z "${PORTAL_SOURCE_ROOT_73}" ]; then
		rm -f metadata-73x.zip
		zip -jqqr metadata-73x.zip $(dirname $PORTAL_SOURCE_ROOT_73)/metadata
		s3upload metadata-73x.zip
	fi
fi