#!/bin/bash

if [ -z "${S3_BUCKET}" ]; then
	echo "Please set a S3_BUCKET for the build"
	exit 1
fi

if [ -z "${AWS_PROFILE}" ]; then
	AWS_PROFILE=default
fi

s3cp() {
	if [[ "$1" == *.gz ]]; then
		aws s3 --profile $AWS_PROFILE cp "${1}" "s3://$S3_BUCKET/${1}" --acl public-read --metadata-directive REPLACE
	else
		rm -f "${1}.gz"
		gzip -c "${1}" > "${1}.gz"

		if [[ ${1} == *.html ]]; then
			aws s3 --profile $AWS_PROFILE cp "${1}.gz" "s3://$S3_BUCKET/${1}" --acl public-read --metadata-directive REPLACE --content-encoding gzip --content-type 'text/html; charset=utf-8'
		else
			aws s3 --profile $AWS_PROFILE cp "${1}.gz" "s3://$S3_BUCKET/${1}" --acl public-read --metadata-directive REPLACE --content-encoding gzip
		fi

		rm "${1}.gz"
	fi
}

s3cp "$@"