#!/bin/bash

deletebranches() {
	local remote_url=$(git remote -v | grep "^${1}\s" | awk '{ print $2 }' | uniq)
	local remote_branches=$(git for-each-ref --format='%(refname)' refs/remotes/$1)

	if [ "git@github.com:liferay/liferay-portal.git" == "$remote_url" ]; then
		echo "$remote_branches" | grep -v '/master$'
	elif [ "git@github.com:liferay/liferay-portal-ee.git" == "$remote_url" ]; then
		echo "$remote_branches" | grep -v '/master-private$' | grep -v '/ee-[0-9]*\.[0-9]*\.x$' | grep -v '/7.0.x$' | grep -v '/7.0.x-private$'
		echo "$remote_branches" | grep '/ee-7.0.x$'
	elif [ "git@github.com:liferay/liferay-plugins.git" == "$remote_url" ]; then
		echo "$remote_branches" | grep -v '/master$' | grep -v '/ee-[0-9]*\.[0-9]*\.x$'
	elif [ "git@github.com:liferay/liferay-plugins-ee.git" == "$remote_url" ]; then
		echo "$remote_branches" | grep -v '/ee-[0-9]*\.[0-9]*\.x$' | grep -v '/ee-[0-9]*\.[0-9]*\.[0-9]*$'
	else
		echo "$remote_branches" | grep -v '/master$' | grep -v '/master-private$' | grep -v '/7.0.x-private$'
	fi
}

fixupstream() {
	local GIT_VERSION=$(git --version | awk '{ print $3 }' | cut -d'.' -f 1)$(git --version | awk '{ print $3 }' | cut -d'.' -f 2 | xargs printf "%03d")

	for remote in $(git remote | grep upstream); do
		local remote_url=$(git remote -v | grep "^${remote}\s" | awk '{ print $2 }' | uniq)
		delete_branches=$(deletebranches $remote | cut -d'/' -f 4)

		for delete_branch in $delete_branches; do
			git branch -d -r $remote/$delete_branch
		done

		retain_branches=$(retainbranches "$remote" | cut -d'/' -f 3-)

		if [ "" != "$retain_branches" ]; then
			git remote set-branches $remote $(echo "$retain_branches" | tr '\n' ' ')
		fi

		if [ "" != "$(git remote | grep origin)" ]; then
			for branch in $retain_branches; do
				pushorigin $branch $remote
			done
		fi
	done

	for remote in $(git remote | grep upstream); do
		git fetch --no-tags $remote --prune
	done


	for remote in $(git remote | grep origin); do
		git fetch $remote --prune
	done

	git prune

	return 0
}

pushorigin() {
	"$(dirname "${BASH_SOURCE[0]}")/pushorigin" "$1" "$2"
}

retainbranches() {
	local remote_url=$(git remote -v | grep "^${1}\s" | awk '{ print $2 }' | uniq)
	local remote_branches=$(git ls-remote -h $1 | awk '{ print $2 }')

	if [ "git@github.com:liferay/liferay-portal.git" == "$remote_url" ]; then
		echo "$remote_branches" | grep '/master$'
	elif [ "git@github.com:liferay/liferay-portal-ee.git" == "$remote_url" ]; then
		echo "$remote_branches" | grep '/master-private$'
		echo "$remote_branches" | grep '/ee-[0-9]*\.[0-9]*\.x$' | grep -v '/ee-7.0.x$'
		echo "$remote_branches" | grep '/7.0.x$'
		echo "$remote_branches" | grep '/7.0.x-private$'
	elif [ "git@github.com:liferay/liferay-plugins.git" == "$remote_url" ]; then
		echo "$remote_branches" | grep '/master$'
		echo "$remote_branches" | grep '/ee-[0-9]*\.[0-9]*\.x$'
	elif [ "git@github.com:liferay/liferay-plugins-ee.git" == "$remote_url" ]; then
		echo "$remote_branches" | grep '/ee-[0-9]*\.[0-9]*\.x$'
		echo "$remote_branches" | grep '/ee-[0-9]*\.[0-9]*\.[0-9]*$'
	else
		echo "$remote_branches" | grep '/master$'
		echo "$remote_branches" | grep '/master-private$'
		echo "$remote_branches" | grep '/7.0.x-private$'
	fi
}

fixupstream