#!/bin/bash

if [[ "$1" != https://github.com/* ]]; then
	echo "$1 does not look like a pull request URL"
	exit 1
fi

hub checkout $@

endpoint=$(echo $1 | cut -d'/' -f 4,5)
pull_id=$(echo $1 | cut -d'/' -f 7)

curl -H "Authorization: token $(git config github.oauth-token)" -s https://api.github.com/repos/$endpoint/pulls/$pull_id | jq '.base.ref'

upstream_remote=$(git for-each-ref --format='%(refname)' refs/remotes/ | grep "/upstream[^/]*/${BASE_BRANCH}$" | cut -d'/' -f 3)

if [ "" == "$upstream_remote" ] && [ -f "$GIT_ROOT/release.properties" ]; then
	. $(dirname "${BASH_SOURCE[0]}")/../getparent
	upstream_remote=$(git for-each-ref --format='%(refname)' refs/remotes/ | grep "/upstream[^/]*/${BASE_BRANCH}$" | cut -d'/' -f 3)
fi

if [ "" == "$upstream_remote" ]; then
	echo "Unable to identify upstream equivalent of $BASE_BRANCH"
	exit 1
fi

git fetch --no-tags ${upstream_remote}
git rebase ${upstream_remote}/${BASE_BRANCH}