#!/bin/bash

pushorigin() {
	local origin_name=origin

	if [ "" != "$2" ]; then
		if [[ "$2" == origin* ]]; then
			origin_name=$2
		else
			local remote_url=$(git remote -v | grep "^${2}\s" | awk '{ print $2 }' | uniq)

			if [ "" == "$upstream_url" ]; then
				echo "Unable to determine origin corresponding to $2"
				return 1
			fi

			origin_name=$(git remote -v | grep -F $(echo $upstream_url | cut -d'/' -f 2) | grep -vF $upstream_url | awk '{ print $1 }' | uniq)

			if [ "" == "$origin_name" ]; then
				return 0
			fi
		fi
	fi

	echo "Updating $1 on $origin_name"

	if [ "" == "$(git for-each-ref --format='%(refname)' refs/heads/$1)" ]; then
		git fetch $2 --no-tags $1:$1
	fi

	if [ "" == "$(git for-each-ref --format='%(refname)' refs/remotes/$origin_name/$1)" ]; then
		for commit in $(git log --reverse --pretty='%H' $1 | awk 'NR % 10000 == 0'); do
			git push $origin_name $commit:refs/heads/$1
		done
	else
		for commit in $(git log --reverse --pretty='%H' $origin_name/$1..$1 | awk 'NR % 10000 == 0'); do
			git push $origin_name $commit:refs/heads/$1
		done
	fi

	git push $origin_name $1:$1
}

pushorigin $1 $2