#!/bin/bash

if [ -d /var/lib/docker ]; then
	sudo mv /var/lib/docker /mnt/
elif [ ! -d /mnt/docker ]; then
	sudo mkdir /mnt/docker
fi

sudo ln -s /mnt/docker /var/lib/docker

sudo apt-get install apache2 docker docker.io

sudo service apache2 start
sudo chown $USER:$USER /var/www/html
sudo rm /var/www/html/index.html

sudo service docker start
sudo usermod -aG docker $USER

sudo mkdir /mnt/github
sudo chown $USER:$USER /mnt/github

git clone https://github.com/holatuwol/liferay-faster-deploy.git /mnt/github/liferay-faster-deploy

docker run --name jupyter --volume /mnt/github/liferay-faster-deploy/jira:/home/jovyan/jira \
	--detach -p 127.0.0.1:8888:8888 jupyter/datascience-notebook \
	start-notebook.sh --NotebookApp.token=''

docker exec -t lesadb mkdir /data

docker network create lesadata
docker network connect --alias jupyter lesadata jupyter