#!/bin/bash

VCS_ROOT=$(git rev-parse --show-toplevel)

MODULES_HOME=

if [ -f $VCS_ROOT/modules/build.gradle ]; then
	MODULES_HOME=$VCS_ROOT/modules
elif [ -f $VCS_ROOT/build.gradle ]; then
	MODULES_HOME=$VCS_ROOT
else
	return 0
fi

if [ -f "$MODULES_HOME/build.gradle.bak" ]; then
	rm $MODULES_HOME/build.gradle
	mv $MODULES_HOME/build.gradle.bak $MODULES_HOME/build.gradle
fi