#!/bin/bash

modulerun() {
	module_npminstall
	module_gulpbuild
}

module_gulpbuild() {
	cat /dev/null > ${cache_home}/cachenpm.gwargs

	for folder in $(cat ${cache_home}/cachenpm.txt | dirnames); do
		if [ -d $folder/node_modules ] && [[ 0 -ne $(ls $folder/node_modules/ | grep -c '^') ]] && [ -f $folder/gulpfile.js ]; then
			echo "$folder" | cut -d'/' -f 2- | tr '/' ':' | awk '{ print ":" $1 ":gulpBuild" }' >> ${cache_home}/cachenpm.gwargs
		fi
	done

	rungradlew
}

module_npminstall() {
	pushd modules

	cat ${cache_home}/cachenpm.txt | dirnames | cut -d'/' -f 2- | tr '/' ':' | awk '{ print ":" $1 ":npmInstall" }' > ${cache_home}/cachenpm.gwargs

	rungradlew

	popd > /dev/null
}

rungradlew() {
	if [[ 0 -ne "$(grep -c '^' ${cache_home}/cachenpm.gwargs)" ]]; then
		cat ${cache_home}/cachenpm.gwargs | xargs ${GIT_ROOT}/gradlew --continue
	fi
}

modulerun