#!/bin/bash

modulerun() {
	modulerungw
	modulerunyarn
	modulerungulp
}

modulerungulp() {
	cat /dev/null > ${cache_home}/cachenpm.gwargs

	for folder in $(cat ${cache_home}/cachenpm.txt | dirnames); do
		if [ -d $folder/node_modules ] && [[ 0 -ne $(ls $folder/node_modules/ | grep -c '^') ]] && [ -f $folder/gulpfile.js ]; then
			echo "$folder" | cut -d'/' -f 2- | tr '/' ':' | awk '{ print ":" $1 ":gulpBuild" }' >> ${cache_home}/cachenpm.gwargs
		fi
	done

	if [[ 0 -ne "$(grep -c '^' ${cache_home}/cachenpm.gwargs)" ]]; then
		cat ${cache_home}/cachenpm.gwargs | xargs $(dirname "${BASH_SOURCE[0]}")/../gw --continue
	fi
}

modulerungw() {
	pushd modules

	cat ${cache_home}/cachenpm.txt | dirnames | cut -d'/' -f 2- | tr '/' ':' | awk '{ print ":" $1 ":npmInstall" }' > ${cache_home}/cachenpm.gwargs

	if [[ 0 -ne "$(grep -c '^' ${cache_home}/cachenpm.gwargs)" ]]; then
		cat ${cache_home}/cachenpm.gwargs | xargs $(dirname "${BASH_SOURCE[0]}")/../gw --continue
	fi

	popd > /dev/null
}

modulerunyarn() {
	if [ "" == "$(which yarn)" ]; then
		return 0
	fi

	for folder in $(cat ${cache_home}/cachenpm.txt | dirnames); do
		if [ ! -d $folder/node_modules ] || [[ 0 -eq $(ls $folder/node_modules/ | grep -c '^') ]]; then
			pushd $folder > /dev/null
			yarn
			popd > /dev/null
		fi
	done
}

modulerun