#!/bin/bash

TIMESTAMP=$(date +%Y%m%d)

pushd $(dirname "${BASH_SOURCE[0]}") > /dev/null
SCRIPT_FOLDER=$(pwd -P)
popd > /dev/null

branch() {
	BASE_BRANCH=$1
	local WORKING_DIR=$2
	local PORT_PREFIX=$3

	echo "Considering ${BASE_BRANCH} branch for rebuild"

	# If we've already built the branch today, no need to rebuild it

	if [ -f "/var/www/html/builds/branches/${WORKING_DIR}-${TIMESTAMP}.tar.gz" ]; then
		echo "Already built ${BASE_BRANCH} for ${TIMESTAMP}"
		return 0
	fi

	# We flag whether or not we want to build a branch by making a folder,
	# so if that folder does not exist, don't bother

	if [ ! -d "$BUILD_FOLDER_PREFIX/$WORKING_DIR" ]; then
		echo "Skipping ${BASE_BRANCH} because $BUILD_FOLDER_PREFIX/$WORKING_DIR does not exist"
		return 0
	fi

	# Execute the build

	local BASE_URL=

	if [ "${BASE_BRANCH}" == "master" ]; then
		BASE_URL='http://mirrors.lax.liferay.com/releases.liferay.com/portal/snapshot-master/latest'
	else
		BASE_URL="http://mirrors.lax.liferay.com/files.liferay.com/private/ee/portal/snapshot-${BASE_BRANCH}/latest"
	fi

	local BASE_NAME="liferay-portal-tomcat-${BASE_BRANCH}-all"

	cd "${BUILD_FOLDER_PREFIX}/${WORKING_DIR}"

	if [ -f /usr/bin/7z ]; then
		curl -O "${BASE_URL}/${BASE_NAME}.7z"
		7z x "${FILE_URL}.7z"
	elif [ -f /usr/bin/7za ]; then
		curl -O "${BASE_URL}/${BASE_NAME}.7z"
		7za x "${FILE_URL}.7z"
	else
		curl -O "${BASE_URL}/${BASE_NAME}.tar.gz"
		tar -zxf "${FILE_URL}.tar.gz"
	fi

	rm "${BASE_NAME}.*"
	mv "$(echo ${BASE_NAME} | sed 's/tomcat-all/all/g')" ${TIMESTAMP}
	cd -

	cd "${BUILD_FOLDER_PREFIX}/${WORKING_DIR}/${TIMESTAMP}"
	tar -cf ${BASE_BRANCH}-${TIMESTAMP}.tar *
	gzip ${BASE_BRANCH}-${TIMESTAMP}.tar
	rm /var/www/html/builds/branches/${BASE_BRANCH}-*.tar.gz
	mv ${BASE_BRANCH}-${TIMESTAMP}.tar.gz /var/www/html/builds/branches/
	cd -
}

branches() {
	if [ ! -d /var/www/html/builds/branches ]; then
		echo "No archive folder for branches, skipping"
		return 0
	fi

	# Clear out the data folder for all past builds

	for folder in $REBUILD; do
		if [ -d $BUILD_FOLDER_PREFIX/$folder ]; then
			for BUILD_ID in $(ls -1 "$BUILD_FOLDER_PREFIX/$folder/" | grep -vF '.log'); do
				rm -rf "$BUILD_FOLDER_PREFIX/$folder/$BUILD_ID/data"
			done
		fi
	done

	# Start build

	echo Started $(date)

	# Build all branches

	for folder in $REBUILD; do
		if [ "master" == "$folder" ]; then
			branch master master-private
			branch master master 60
		elif [ "73x" == "$folder" ]; then
			branch 7.3.x 73x 73x
			branch 7.3.x 73x-private 73
		elif [ "72x" == "$folder" ]; then
			branch 7.2.x 72x 72x
			branch 7.2.x 72x-private 72
		elif [ "71x" == "$folder" ]; then
			branch 7.1.x 71x 71x
			branch 7.1.x 71x-private 71
		elif [ "70x" == "$folder" ]; then
			branch 7.0.x 70x 70x
			branch 7.0.x 70x-private 70
		elif [ "62x" == "$folder" ]; then
			branch ee-6.2.x 62x 62
		elif [ "61x" == "$folder" ]; then
			branch ee-6.1.x 61x 61
		fi
	done

	echo Completed $(date)
}

checkout() {
	local WORKTREE_FOLDER=

	if [ -d .git/worktrees ]; then
		WORKTREE_FOLDER=$PWD/.git/worktrees
	elif [ -f .git ]; then
		WORKTREE_FOLDER=$(dirname "$(cut -d' ' -f 2 .git)")
	fi

	if [ "" != "$WORKTREE_FOLDER" ]; then
		for worktree in $WORKTREE_FOLDER/*; do
			if [ "refs/heads/$1" == "$(cut -d' ' -f 2 "${worktree}/HEAD")" ]; then
				cd "$(dirname "$(cat "${worktree}/gitdir")")"
			fi
		done
	fi

	git clean -xdf
	git reset --hard

	echo "Running git checkout $1"
	git checkout -f $1

	if [[ $1 == *-private ]]; then
		git log -1 $(git branch | cut -d')' -f 1 | grep -F '*' | cut -d' ' -f 5 | sed 's/-private$//') --pretty='%H' > git-commit-portal
	fi
}

fixpack() {
	# If we have not checked out the tag locally, make sure to check it out

	if [ "" == "$(git tag | grep -F "$1")" ]; then
		if [[ $1 == fix-pack-* ]]; then
			git fetch --no-tags git@github.com:liferay/liferay-portal-ee.git tags/$1:refs/tags/$1
		else
			git fetch --no-tags git@github.com:liferay/liferay-portal.git tags/$1:refs/tags/$1
		fi

		if [ "" == "$(git tag | grep -F "$1")" ]; then
			echo "Unable to find tag ${1}"
			return 1
		fi
	fi

	# If we've already built the fixpack, no need to rebuild it

	if [ -f "/var/www/html/builds/fixpacks/${1}.tar.gz" ]; then
		echo "Already built ${1}"
		return 0
	fi

	checkout $1

	# Execute the build

	BUILD_FOLDER_PREFIX="$BUILD_FOLDER_PREFIX/temp" \
		BUILD_FOLDER_SUFFIX="" \
		ARCHIVE_FOLDER="/var/www/html/builds/fixpacks" \
		TIMESTAMP="" \
			$SCRIPT_FOLDER/prepare $1 80

	# Remove the temp folder where we were building to

	rm -rf "$BUILD_FOLDER_PREFIX/temp/$1"
}

fixpacks() {
	if [ ! -d /var/www/html/builds/fixpacks ]; then
		echo "No archive folder for fixpacks, skipping"
		return 0
	fi

	git ls-remote -t git@github.com:liferay/liferay-portal.git | \
		awk '{ print $2 }' | grep '/[0-9]*.[0-9]*.[0-9]*-ga[0-9]*$' \
		sort | cut -d'/' -f 3 > /var/www/html/builds/fixpacks/tags-ce.txt

	for tag_id in $(cat /var/www/html/builds/fixpacks/tags-ce.txt); do
		fixpack $tag_id
	done

	git ls-remote -t git@github.com:liferay/liferay-portal-ee.git | \
		awk '{ print $2 }' | grep -e '/fix-pack-base-[0-9]*\(-private\)*$' | \
		sort -t'-' -nk4 | cut -d'/' -f 3 > /var/www/html/builds/fixpacks/tags.txt

	git ls-remote -t git@github.com:liferay/liferay-portal-ee.git | \
		awk '{ print $2 }' | grep -e '/fix-pack-\(de\|dxp\)-[0-9]*-[0-9]*\(-private\)*$' | \
		sort -t'-' -nk5 -nk4 | cut -d'/' -f 3 >> /var/www/html/builds/fixpacks/tags.txt

	for tag_id in $(cat /var/www/html/builds/fixpacks/tags.txt); do
		fixpack $tag_id
	done
}

setportalcommit() {
	echo -e "\n\nUpdating git-commit-portal commit"

	echo git log -1 --pretty='%H' $(echo $1 | sed 's/-private$//g')
	git log -1 --pretty='%H' $(echo $1 | sed 's/-private$//g') | tee git-commit-portal

	ant -f build-working-dir.xml
}

update() {
	$SCRIPT_FOLDER/../github/fixupstream

	if [ "" == "$(git remote | grep '^upstream$')" ]; then
		git fetch origin --no-tags
	else
		for remote in $(git remote | grep '^upstream'); do
			git fetch $remote --no-tags
		done
	fi

	git reflog expire --expire=now --all
	git gc --prune
	return 0
}

if [ -z "${PORTAL_SOURCE_ROOT}" ]; then
	echo "Please set a PORTAL_SOURCE_ROOT for the build"
	exit 1
fi

if [ ! -e "$PORTAL_SOURCE_ROOT/.git" ]; then
	echo "${PORTAL_SOURCE_ROOT} is not a git repository"
	exit 1
fi

if [ -z "${BUILD_FOLDER_PREFIX}" ]; then
	echo "Please set a BUILD_FOLDER_PREFIX for the build"
	exit 1
fi

REBUILD="$@"

if [ "" == "$REBUILD" ]; then
	REBUILD="master 73x 72x 71x 70x 62x 61x"
fi

for cache in liferay-binaries-cache-2017 liferay-binaries-cache-2020; do
	if [ ! -e $(dirname $PORTAL_SOURCE_ROOT)/${cache} ]; then
		pushd $(dirname $PORTAL_SOURCE_ROOT)
		git clone git@github.com:liferay/${cache}.git
	fi

	cd $(dirname $PORTAL_SOURCE_ROOT)/${cache}
	git clean -xdf
	git reset --hard
done

cd $PORTAL_SOURCE_ROOT
update
branches
fixpacks