#!/bin/bash

TIMESTAMP=$(date +%Y%m%d)

USER=$(whoami)
HOME=/home/${USER}
SCRIPT_FOLDER=${HOME}/crontab

download_branch() {
	rm -rf ${HOME}/${1}
	mkdir -p ${HOME}/${1}
	cd ${HOME}/${1}

	curl -O http://mirrors.lax.liferay.com/releases.liferay.com/portal/snapshot-${2}/latest/liferay-portal-tomcat-${2}-all.${3}

	if [ "7z" == "${3}" ]; then
		7z x liferay-portal-tomcat-${2}-all.${3}
	elif [ "zip" == "${3}" ]; then
		unzip -qq liferay-portal-tomcat-${2}-all.${3}
	else
		tar -zxf liferay-portal-tomcat-${2}-all.${3}
	fi

	mv liferay-portal-${2}-all ${TIMESTAMP}
}

download_branch master-private master 7z
download_branch 73x-private 7.3.x-private 7z
download_branch 72x-private 7.2.x-private 7z
download_branch 71x-private 7.1.x-private 7z
download_branch 70x-private 7.0.x-private zip

source "${HOME}/crontab/aliases"

crall