#!/bin/bash

cd ${HOME}

S3_BUCKET=$(cat bucket.txt)

aws s3 cp s3://$S3_BUCKET/gh/source.tar .
tar -xf source.tar
rm source.tar

for folder in source liferay-binaries-cache-2017 liferay-binaries-cache-2020; do
	cd ${HOME}/${folder}
	git checkout .
	git gc --no-prune
done