#!/bin/bash

cd $HOME

S3_BUCKET=$(cat bucket.txt)

# Download from mirrors

clone_repo() {
	local target_folder=${2}

	if [ "" == "${2}" ]; then
		target_folder=${1}
	fi

	if [ -d ${target_folder}/.git ]; then
		cd ${target_folder}
		git clean -xdf
		git gc --no-prune
		cd -
		return 0
	fi

	wget http://mirrors/github.com/liferay/${1}.tar.gz
	tar -zxf ${1}.tar.gz
	rm ${1}.tar.gz

	if [ "${1}" == "${target_folder}" ]; then
		return 0
	fi

	mv ${1} ${target_folder}
}

clone_repo liferay-portal-ee source

# Remove origin and tags to make the build smaller

cd source
git remote rm origin
(git tag | xargs git tag -d) > /dev/null
cd -

for cache in liferay-binaries-cache-2017 liferay-binaries-cache-2020; do
	clone_repo ${cache}
done

# Create a new archive

tar -cf source.tar source/.git liferay-binaries-cache-2017/.git liferay-binaries-cache-2020/.git
aws s3 cp source.tar s3://$S3_BUCKET/gh/
rm source.tar