#!/bin/bash

pushd $(dirname "${BASH_SOURCE[0]}") > /dev/null
SCRIPT_FOLDER=$(pwd -P)
popd > /dev/null

compile() {
	echo "Starting compilation for $1"
	GIT_HASH=$(git log -1 --pretty='%H')

	sed -i 's/\${env.ANT_OPTS}/${env.GRADLE_OPTS}/g' build-common.xml
	git update-index --assume-unchanged build-common.xml

	# Setup properties

	echo "app.server.parent.dir=$LIFERAY_HOME" > app.server.$USER.properties

	ARCHIVE_HOME="$HOME/.liferay/tomcat" \
		$SCRIPT_FOLDER/../appserverprops

	# Begin building

	echo 'Git Hash:' | tee "${LIFERAY_HOME}.log"
	echo "$GIT_HASH" | tee -a "${LIFERAY_HOME}.log"
	echo '' | tee -a "${LIFERAY_HOME}.log"

	if [ -f working.dir.properties ] && [ -f build-working-dir.xml ]; then
		ant -f build-working-dir.xml
	fi

	if [ -f modules/build.gradle ]; then
		$SCRIPT_FOLDER/../skipmp | tee -a "${LIFERAY_HOME}.log"
		$SCRIPT_FOLDER/../nodejs/cachenpm | tee -a "${LIFERAY_HOME}.log"
	fi

	$SCRIPT_FOLDER/../fixbnd

	set -o pipefail
	ant all | tee -a "${LIFERAY_HOME}.log"
	EXIT_CODE=$?
	set +o pipefail

	if [[ $EXIT_CODE -ne 0 ]]; then
		return $EXIT_CODE
	fi

	$SCRIPT_FOLDER/../tomcat/precompile
	return 0
}

finish() {
	local TOMCAT_VERSION=$(grep -F app.server.tomcat.version= app.server.properties | cut -d'=' -f 2)
	TOMCAT_FOLDER=$LIFERAY_HOME/tomcat-${TOMCAT_VERSION}

	cp tools/servers/tomcat/bin/setenv.* $TOMCAT_FOLDER/bin
	sed -i 's/@.*@ //g' $TOMCAT_FOLDER/bin/setenv.sh
	sed -i 's/@.*@ //g' $TOMCAT_FOLDER/bin/setenv.bat

	echo -en '\nGIT_HASH="'$GIT_HASH'"' >> $TOMCAT_FOLDER/bin/setenv.sh
	echo -en '\r\nset GIT_HASH="'$GIT_HASH'"' >> $TOMCAT_FOLDER/bin/setenv.bat

	echo -en '\nCATALINA_OPTS="$CATALINA_OPTS -Denv.COMPUTERNAME='$1'-$GIT_HASH"' >> $TOMCAT_FOLDER/bin/setenv.sh
	echo -en '\r\nset "CATALINA_OPTS=%CATALINA_OPTS% -Denv.COMPUTERNAME='$1'-%GIT_HASH%"' >> $TOMCAT_FOLDER/bin/setenv.bat

	echo -en '\n#JAVA_HOME=' >> $TOMCAT_FOLDER/bin/setenv.sh
	echo -en '\r\nrem set JAVA_HOME=' >> $TOMCAT_FOLDER/bin/setenv.bat

	echo -en '\nPATH=$JAVA_HOME/bin:$PATH' >> $TOMCAT_FOLDER/bin/setenv.sh
	echo -en '\r\nset PATH="%JAVA_HOME%\\bin;%PATH%"' >> $TOMCAT_FOLDER/bin/setenv.bat

	if [ "ee-6.2.x" == "$BASE_BRANCH" ] || [ "ee-6.1.x" == "$BASE_BRANCH" ]; then
		sed -i 's/-Xmx[0-9]*[gm]/-Xms1g -Xmx1g/g' $TOMCAT_FOLDER/bin/setenv.sh
		sed -i 's/-Xmx[0-9]*[gm]/-Xms1g -Xmx1g/g' $TOMCAT_FOLDER/bin/setenv.bat
	else
		sed -i 's/-Xmx[0-9]*[gm]/-Xms2g -Xmx2g/g' $TOMCAT_FOLDER/bin/setenv.sh
		sed -i 's/-Xmx[0-9]*[gm]/-Xms2g -Xmx2g/g' $TOMCAT_FOLDER/bin/setenv.bat
	fi

	sed -i 's/ start / jpda start /g' $TOMCAT_FOLDER/bin/startup.sh
	sed -i 's/ start / jpda start /g' $TOMCAT_FOLDER/bin/startup.bat

	chmod u+x $TOMCAT_FOLDER/bin/*.sh

	pushd $LIFERAY_HOME

	dos2unix $TOMCAT_FOLDER/bin/setenv.sh
	dos2unix $TOMCAT_FOLDER/bin/startup.sh

	unix2dos $TOMCAT_FOLDER/bin/setenv.bat
	unix2dos $TOMCAT_FOLDER/bin/startup.bat

	if [ -d "${ARCHIVE_FOLDER}" ]; then
		find ${ARCHIVE_FOLDER} -name "${1}-[0-9]*.tar.gz" | xargs rm

		if [ "" != "$TIMESTAMP" ]; then
			tar -zcf ${ARCHIVE_FOLDER}/${1}-${TIMESTAMP}.tar.gz *
		else
			tar -zcf ${ARCHIVE_FOLDER}/${1}.tar.gz *
		fi
	fi

	if [ -d /var/www/html/logs ] && [ "" != "$TIMESTAMP" ]; then
		rm /var/www/html/logs/$1
		ln -s "$LIFERAY_HOME" /var/www/html/logs/$1
	fi

	popd

	sed -i "s@#JAVA_HOME=@JAVA_HOME=$JAVA_HOME@g" $TOMCAT_FOLDER/bin/setenv.sh

	if [ "" != "$2" ]; then
		switchport 80 $2
	fi
}

javahome() {
	. $SCRIPT_FOLDER/../javahome $@
}

prepare() {
	BASE_BRANCH=ee-$(grep -F 'lp.version.major=' release.properties | cut -d'=' -f 2).x
	JSP_JAVA_VERSION=

	if [ "ee-6.2.x" == "$BASE_BRANCH" ]; then
		export ANT_OPTS='-Xms2g -Xmx2g -XX:MaxPermSize=512m'
		javahome 6
	elif [ "ee-6.1.x" == "$BASE_BRANCH" ]; then
		export ANT_OPTS='-Xms2g -Xmx2g -XX:MaxPermSize=512m'
		javahome 6
	else
		export GRADLE_OPTS='-Xms4g -Xmx4g -Dorg.gradle.workers.max=1'
		export ANT_OPTS='-Xms2g -Xmx2g'
		javahome 8
	fi

	echo $JAVA_HOME

	compile $1 && finish $1 $2

	if [ -d "${ARCHIVE_FOLDER}" ]; then
		if [ "" != "$TIMESTAMP" ]; then
			cp "${LIFERAY_HOME}.log" ${ARCHIVE_FOLDER}/$1-${TIMESTAMP}.log
		else
			cp "${LIFERAY_HOME}.log" ${ARCHIVE_FOLDER}/$1.log
		fi
	fi
}

switchport() {
	if [ "" == "$(grep JPDA_ADDRESS= $TOMCAT_FOLDER/bin/setenv.sh)" ]; then
		echo -e "\nJPDA_ADDRESS=${1}00" >> $TOMCAT_FOLDER/bin/setenv.sh
		echo -e "\r\nset JPDA_ADDRESS=${1}00" >> $TOMCAT_FOLDER/bin/setenv.bat
	fi

	sed -i "s/\"$1/\"$2/g" $TOMCAT_FOLDER/conf/server.xml
	sed -i "s/JPDA_ADDRESS=${1}/JPDA_ADDRESS=${2}/g" $TOMCAT_FOLDER/bin/setenv.sh
	sed -i "s/JPDA_ADDRESS=${1}/JPDA_ADDRESS=${2}/g" $TOMCAT_FOLDER/bin/setenv.bat
}

if [ -z "${BUILD_FOLDER_PREFIX}" ]; then
	echo "Please set a BUILD_FOLDER_PREFIX for the build"
	exit 1
fi

if [ -z "${ARCHIVE_FOLDER}" ]; then
	echo "Please set a ARCHIVE_FOLDER for the build"
	exit 1
fi

if [ ! -z "${BUILD_FOLDER_SUFFIX}" ] && [ "/" != "$BUILD_FOLDER_SUFFIX" ]; then
	LIFERAY_HOME="$BUILD_FOLDER_PREFIX/$1/$BUILD_FOLDER_SUFFIX"
else
	LIFERAY_HOME="$BUILD_FOLDER_PREFIX/$1"
fi

prepare $@