#!/bin/bash

S3_BUCKET=$(cat $HOME/bucket.txt)
TIMESTAMP=$(date +%F)

echo "Syncing files for ${TIMESTAMP} from ${S3_BUCKET}"

aws s3 cp s3://${S3_BUCKET}/github.sql.gz /var/www/html/data/github-${TIMESTAMP}.sql.gz
aws s3 cp s3://${S3_BUCKET}/checkgh.tar.gz /var/www/html/data/github_rawdata-${TIMESTAMP}.tar.gz

if [[ 5 -lt $(ls -1 /var/www/html/data/github_lportal-* | wc -l) ]]; then
     ls -1 /var/www/html/data/github_lportal-* | sort | head -n -5 | xargs rm
fi

if [[ 5 -lt $(ls -1 /var/www/html/data/github_rawdata-* | wc -l) ]]; then
     ls -1 /var/www/html/data/github_rawdata-* | sort | head -n -5 | xargs rm
fi
