#!/bin/bash

PORTAL_SOURCE_PUBLIC=${HOME}/Work/liferay/7.1.x/portal
PORTAL_SOURCE_PRIVATE=${HOME}/Work/liferay/7.1.x/private

COMMERCE_SOURCE_PUBLIC=${HOME}/Work/liferay/subrepos/com-liferay-commerce
COMMERCE_SOURCE_PRIVATE=${HOME}/Work/liferay/subrepos/com-liferay-commerce-private

COMMERCE_BASE_VERSION=1.1.6-7110
COMMERCE_PUBLIC_CHANGES=origin/7.1.x-next
COMMERCE_PRIVATE_CHANGES=origin/7.1.x-private-next

patch_public() {
	if [ "" == "${COMMERCE_PUBLIC_CHANGES}" ]; then
		return 0
	fi

	cd ${PORTAL_SOURCE_PUBLIC}
	git clean -xdf
	git reset --hard
	git checkout -f marketplace-commerce-${COMMERCE_BASE_VERSION}

	local PUBLIC_HASH=$(grep 'commit =' modules/apps/commerce/.gitrepo | awk '{ print $3 }')

	cd ${COMMERCE_SOURCE_PUBLIC}

	git fetch origin --no-tags
	rm -f *.patch
	git format-patch ${PUBLIC_HASH}..${COMMERCE_PUBLIC_CHANGES}
	sed -i.bak 's@ a/@ a/modules/apps/commerce/@g' *.patch
	sed -i.bak 's@ b/@ b/modules/apps/commerce/@g' *.patch
	sed -i.bak 's@^rename from @rename from modules/apps/commerce/@g' *.patch
	sed -i.bak 's@^rename to @rename to modules/apps/commerce/@g' *.patch
	sed -i.bak '/=>/s@^rename @rename modules/apps/commerce/@g' *.patch

	mv *.patch ${PORTAL_SOURCE_PUBLIC}/
	cd ${PORTAL_SOURCE_PUBLIC}
	apply_patch_files
}

patch_private() {
	if [ "" == "${COMMERCE_PRIVATE_CHANGES}" ]; then
		return 0
	fi

	cd ${PORTAL_SOURCE_PRIVATE}
	git clean -xdf
	git reset --hard
	git checkout -f marketplace-commerce-${COMMERCE_BASE_VERSION}-private

	local PRIVATE_HASH=$(grep 'commit =' modules/private/apps/commerce/.gitrepo | awk '{ print $3 }')

	cd ${COMMERCE_SOURCE_PRIVATE}
	git fetch origin --no-tags
	rm -f *.patch
	git format-patch ${PRIVATE_HASH}..origin/${COMMERCE_PRIVATE_CHANGES}
	sed -i.bak 's@ a/@ a/modules/private/apps/commerce/@g' *.patch
	sed -i.bak 's@ b/@ b/modules/private/apps/commerce/@g' *.patch
	sed -i.bak 's@^rename from @rename from modules/private/apps/commerce/@g' *.patch
	sed -i.bak 's@^rename to @rename to modules/private/apps/commerce/@g' *.patch
	sed -i.bak '/=>/s@^rename @rename modules/private/apps/commerce/@g' *.patch

	mv *.patch ${PORTAL_SOURCE_PRIVATE}/
	cd ${PORTAL_SOURCE_PRIVATE}
	apply_patch_files
}

apply_patch_files() {
	ls *.patch | sort | xargs git am
}

patch_public && patch_private