#!/bin/bash

PORTAL_SOURCE_PUBLIC=${HOME}/Work/liferay/7.1.x/portal
PORTAL_SOURCE_PRIVATE=${HOME}/Work/liferay/7.1.x/private

COMMERCE_SOURCE_PUBLIC=${HOME}/Work/liferay/subrepos/com-liferay-commerce
COMMERCE_SOURCE_PRIVATE=${HOME}/Work/liferay/subrepos/com-liferay-commerce-private

COMMERCE_BASE_VERSION=1.1.6-7110
COMMERCE_PUBLIC_CHANGES=2.0.1
COMMERCE_PRIVATE_CHANGES=2.0.1

patch_public() {
	if [ "" == "${COMMERCE_PUBLIC_CHANGES}" ]; then
		return 0
	fi

	cd ${PORTAL_SOURCE_PUBLIC}
	git clean -xdf
	git reset --hard
	git checkout -f marketplace-commerce-${COMMERCE_BASE_VERSION}

	if [[ ${COMMERCE_PUBLIC_CHANGES} == origin/* ]]; then
		patch_public_subrepo
	else
		patch_public_branch
	fi
}

patch_public_branch() {
	local PUBLIC_HASH=$(git show 7.1.x:modules/.releng/apps/commerce/app.changelog | grep -F app.git.id-${COMMERCE_PUBLIC_CHANGES}= | cut -d'=' -f 2)
	git format-patch HEAD..${PUBLIC_HASH} -- modules/apps/commerce
	apply_patch_files

	git checkout -b marketplace-commerce-${COMMERCE_PUBLIC_CHANGES}-7110-tmp
}

patch_public_subrepo() {
	local PUBLIC_HASH=$(grep 'commit =' modules/apps/commerce/.gitrepo | awk '{ print $3 }')

	cd ${COMMERCE_SOURCE_PUBLIC}

	git fetch origin --no-tags
	rm -f *.patch
	git format-patch ${PUBLIC_HASH}..${COMMERCE_PUBLIC_CHANGES}
	sed -i.bak 's@ a/@ a/modules/apps/commerce/@g' *.patch
	sed -i.bak 's@ b/@ b/modules/apps/commerce/@g' *.patch
	sed -i.bak 's@^rename from @rename from modules/apps/commerce/@g' *.patch
	sed -i.bak 's@^rename to @rename to modules/apps/commerce/@g' *.patch
	sed -i.bak '/=>/s@^rename @rename modules/apps/commerce/@g' *.patch

	mv *.patch ${PORTAL_SOURCE_PUBLIC}/
	cd ${PORTAL_SOURCE_PUBLIC}
	apply_patch_files
}

patch_private() {
	if [ "" == "${COMMERCE_PRIVATE_CHANGES}" ]; then
		return 0
	fi

	cd ${PORTAL_SOURCE_PRIVATE}
	git clean -xdf
	git reset --hard
	git checkout -f marketplace-commerce-${COMMERCE_BASE_VERSION}-private

	if [[ ${COMMERCE_PUBLIC_CHANGES} == origin/* ]]; then
		patch_private_subrepo
	else
		patch_private_branch
	fi
}

patch_private_branch() {
	local PRIVATE_HASH=$(git show 7.1.x-private:modules/.releng/apps/commerce/app.changelog | grep -F app.git.id-${COMMERCE_PRIVATE_CHANGES}= | cut -d'=' -f 2)
	git format-patch HEAD..${PRIVATE_HASH} -- modules/private/apps/commerce
	apply_patch_files
}

patch_private_subrepo() {
	local PRIVATE_HASH=$(grep 'commit =' modules/private/apps/commerce/.gitrepo | awk '{ print $3 }')

	cd ${COMMERCE_SOURCE_PRIVATE}
	git fetch origin --no-tags
	rm -f *.patch
	git format-patch ${PRIVATE_HASH}..origin/${COMMERCE_PRIVATE_CHANGES}
	sed -i.bak 's@ a/@ a/modules/private/apps/commerce/@g' *.patch
	sed -i.bak 's@ b/@ b/modules/private/apps/commerce/@g' *.patch
	sed -i.bak 's@^rename from @rename from modules/private/apps/commerce/@g' *.patch
	sed -i.bak 's@^rename to @rename to modules/private/apps/commerce/@g' *.patch
	sed -i.bak '/=>/s@^rename @rename modules/private/apps/commerce/@g' *.patch

	mv *.patch ${PORTAL_SOURCE_PRIVATE}/
	cd ${PORTAL_SOURCE_PRIVATE}
	apply_patch_files

	git checkout -b marketplace-commerce-${COMMERCE_PUBLIC_CHANGES}-7110-private-tmp
}

apply_patch_files() {
	ls *.patch | sort | xargs git am
}

patch_public && patch_private