#!/bin/bash

SCRIPT_FOLDER=$(dirname $0)
source ${SCRIPT_FOLDER}/../bin/activate

findbuildurl() {
	. "${SCRIPT_FOLDER}/findbuildurl" $@
}

webbrowser() {
	python $(dirname "${BASH_SOURCE[0]}")/../webbrowser_patch.py "$1"
}

findbuildurl $@

if [ "" != "${BUILD_URL}" ]; then
	echo "${BUILD_URL}"
	webbrowser "${BUILD_URL}"
fi