#!/bin/bash

if [ "" == "$(git config 1password.liferay)" ]; then
	echo "Cannot decode $1 unless 1password.liferay is set with git config --global"
	exit 1
fi

SCRIPT_FOLDER=$(dirname ${BASH_SOURCE[0]})

python "${SCRIPT_FOLDER}/findhotfix.py" $1 | grep -o '^http://files.liferay.com/.*$'