#!/bin/bash

SCRIPT_FOLDER=$(dirname ${BASH_SOURCE[0]})

findbuildurl() {
	. "${SCRIPT_FOLDER}/findbuildurl" $1
}

webbrowser() {
	python $(dirname "${BASH_SOURCE[0]}")/../webbrowser_patch.py "$1"
}

findbuildurl $@

if [ "" != "${BUILD_URL}" ]; then
	webbrowser "${BUILD_URL}"
fi