#!/bin/bash

SCRIPT_FOLDER=$(dirname ${BASH_SOURCE[0]})

findbuildurl() {
	. "${SCRIPT_FOLDER}/findbuildurl" $1
}

findbuildurl $@

if [ "" != "${BUILD_URL}" ]; then
	python -m webbrowser "${BUILD_URL}"
fi