#!/bin/bash

SCRIPT_FOLDER=$(dirname ${BASH_SOURCE[0]})

gethotfix() {
	FIX_PATH=

	if [ -f gradle.properties ] && [ "" != "$(grep '^lr.docker.environment.hotfix.urls=' gradle.properties)" ]; then
		FIX_PATH="configs/common/patching/$(grep '^lr.docker.environment.hotfix.urls=' gradle.properties | grep -o '[^/]*.zip$')"

		if [ -f "${FIX_PATH}" ]; then
			return 0
		fi

		FIX_PATH=
		return 1
	fi

	local FIX_VERSION=

	if [[ "${1}" == *hotfix* ]]; then
		FIX_VERSION="$(echo ${1} | sed 's/-hotfix-.*//g' | sed 's/^[^0-9]*//g')"
	else
		FIX_VERSION="${1}"
	fi

	FIX_VERSION=$(curl -s "https://hotfixes.liferay.com/" | grep -o '<a href="[0-9][^"]*">' | cut -d'"' -f 2 | cut -d'/' -f 1 | fzf --query="${FIX_VERSION}" --exact --select-1)

	if [ "" == "${FIX_VERSION}" ]; then
		FIX_PATH=
		return 1
	fi

	local FIX_NAME=

	if [[ "${1}" == *hotfix* ]]; then
		FIX_NAME="$(echo ${1} | grep -o 'hotfix-.*$')"
	else
		FIX_NAME="${2}"
	fi

	FIX_NAME=$(curl -s "https://hotfixes.liferay.com/${FIX_VERSION}/" | grep -o '<a href="[^"]*">' | cut -d'"' -f 2 | fzf --query="${FIX_NAME}" --exact --select-1)

	if [ "" == "${FIX_NAME}" ]; then
		FIX_PATH=
		return 1
	fi

	FIX_PATH="${HOME}/Downloads/${FIX_NAME}"

	if [ -f "${FIX_PATH}" ]; then
		return 0
	fi

	local FIX_URL="https://hotfixes.liferay.com/${FIX_VERSION}/${FIX_NAME}"
	echo "${FIX_URL}"
	curl --progress-bar "${FIX_URL}" --output "${FIX_PATH}"
}

findbuildurl() {
	gethotfix $@

	if [ "" == "${FIX_PATH}" ] || [ ! -f "${FIX_PATH}" ]; then
		return 1
	fi

	local BUILD_ID=$(unzip -p "${FIX_PATH}" fixpack_documentation.xml 2>/dev/null | grep -F '<build-id>' | cut -d'>' -f 2 | cut -d'<' -f 1)

	if [ "" == "${BUILD_ID}" ]; then
		BUILD_ID=$(unzip -p "${FIX_PATH}" fixpack_documentation.json 2>/dev/null | jq '.build.id' | cut -d'"' -f 2)
	fi

	if [ "" == "${BUILD_ID}" ]; then
		BUILD_ID=$(unzip -p "${FIX_PATH}" hotfix.json 2>/dev/null | jq '.build.id' | cut -d'"' -f 2)
	fi

	if [ "" == "${BUILD_ID}" ]; then
		return 1
	fi

	BUILD_URL="https://patcher.liferay.com/group/guest/patching/-/osb_patcher/builds/${BUILD_ID}"
}

findbuildurl $@