#!/bin/bash

SCRIPT_FOLDER=$(dirname ${BASH_SOURCE[0]})

findbuildurl() {
	. "${SCRIPT_FOLDER}/findbuildurl" $1
	rm -f ${FIX_NAME}.zip
}

convertargs() {
	CONVERTED_ARGS=

	for arg in $@; do
		if [[ ${arg} == http://files.liferay.com/* ]] || [[ ${arg} == https://files.liferay.com/* ]]; then
			if [ "" != "${FILES_MIRROR}" ]; then
				findbuildurl ${arg}
			else
				echo 'Unable to convert hotfix URL to build URL unless FILES_MIRROR environment variable is set'
				exit 1
			fi
		fi

		if [ "" != "${BUILD_URL}" ]; then
			CONVERTED_ARGS="${CONVERTED_ARGS} ${BUILD_URL}"
		else
			CONVERTED_ARGS="${CONVERTED_ARGS} ${arg}"
		fi
	done
}

if [ "" == "$(git config files.username)" ] || [ "" == "$(git config files.password)" ]; then
	echo "Cannot connect to patcher portal and testray API without username and password"
	echo "Set your liferay.com username with git config --global files.username USERNAME"
	echo "Set your liferay.com password with git config --global files.password PASSWORD"
	exit 1
fi

convertargs $@

python "${SCRIPT_FOLDER}/testray.py" ${CONVERTED_ARGS}